obj-$(CONFIG_MTK_SOC_THERMAL)	+= auxadc_thermal.o
obj-$(CONFIG_MTK_LVTS_THERMAL)	+= lvts_thermal.o
obj-$(CONFIG_MTK_PMIC_THERMAL) 	+= pmic_temp.o
obj-$(CONFIG_MTK_LVTS_THERMAL)  += soc_temp_lvts_mt8189.o