# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_MTK_SOC_THERMAL)	+= soc_temp.o
obj-$(CONFIG_MTK_SOC_THERMAL_LVTS)	+= soc_temp_lvts.o
obj-$(CONFIG_MTK_PMIC_THERMAL) += pmic_temp.o