#
# Makefile for TVAFE.
#
obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_AFE) += tvin_afe.o
tvin_afe-objs := tvafe_cvd.o tvafe_general.o tvafe_debug.o tvafe.o

obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_VBI) += tvafe_vbi.o
obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_AVDETECT) += tvin_avin_detect.o
tvin_avin_detect-objs := tvafe_avin_detect.o
