#
# Makefile for the mc13783 pmic drivers.
#

obj-$(CONFIG_MXC_MC34708_ADC) += mc34708_adc.o
#obj-$(CONFIG_MXC_MC34708_RTC) += mc34708_rtc.o
obj-$(CONFIG_MXC_MC34708_LIGHT) += mc34708_light.o
obj-$(CONFIG_MXC_MC34708_BATTERY) += mc34708_battery.o
#obj-$(CONFIG_MXC_MC34708_CONNECTIVITY) += mc34708_convity.o
#obj-$(CONFIG_MXC_MC34708_POWER) += mc34708_power.o
