/* This file contains the required settings for the IQS5XX, for a specific hardware setup
This can be exported from the IQS5XX GUI, or modified here.  It is used in the
IQS5XX_Setup() function to configure the on-chip parameters of the device. */

#ifndef IQS5XX_INIT_H
#define IQS5XX_INIT_H

#define PRODUCT_NUMBER		40
#define PROJECT_NUMBER		0
#define VERSION_NUMBER		56

#define CONTROLSETTINGS0_VAL	0x00
#define CONTROLSETTINGS1_VAL	0x31

#define PROXTHRESHOLD_VAL	10
#define TOUCHMULTIPLIER_VAL	20
#define TOUCHSHIFTER_VAL	7
#define PMPROXTHRESHOLD_VAL	10
#define SNAPTHRESHOLD_VAL	100
#define PROXTHRESHOLD2_VAL	10
#define TOUCHMULTIPLIER2_VAL	20
#define TOUCHSHIFTER2_VAL	7

#define ATITARGET_VAL		250
#define ATIC_VAL		5
#define ATITARGET2_VAL		600
#define ATIC2_VAL		0

#define FILTERSETTINGS0_VAL	0x0A
#define TOUCHDAMPING_VAL	255
#define HOVERDAMPING_VAL	38
#define PMCOUNTDAMPING_VAL	16
#define LPPMCOUNTDAMPING_VAL	128
#define NMCOUNTDAMPING_VAL	1

#define RESEEDTIME_VAL		255
#define COMMSTIMEOUT_VAL	100
#define MODETIME_VAL		8
#define LPTIME_VAL		8
#define SLEEPTIME_VAL		1

#define TOTALRXS_VAL		10
#define TOTALTXS_VAL		15
#define TRACKPADRXS_VAL		10
#define TRACKPADTXS_VAL		15
#define PMSETUP0_VAL		0x40
#define TXHIGH_VAL		0x7F
#define TXLOW_VAL		0xFF

#define PROXSETTINGS0_VAL	0x24
#define PROXSETTINGS1_VAL	0x42
#define PROXSETTINGS2_VAL	0x33
#define PROXSETTINGS3_VAL	0x11

#define ACTIVECHANNELS0_VAL	0x3FF
#define ACTIVECHANNELS1_VAL	0x3FF
#define ACTIVECHANNELS2_VAL	0x3FF
#define ACTIVECHANNELS3_VAL	0x3FF
#define ACTIVECHANNELS4_VAL	0x3FF
#define ACTIVECHANNELS5_VAL	0x3FF
#define ACTIVECHANNELS6_VAL	0x3FF
#define ACTIVECHANNELS7_VAL	0x3FF
#define ACTIVECHANNELS8_VAL	0x3FF
#define ACTIVECHANNELS9_VAL	0x3FF
#define ACTIVECHANNELS10_VAL	0x3FF
#define ACTIVECHANNELS11_VAL	0x3FF
#define ACTIVECHANNELS12_VAL	0x3FF
#define ACTIVECHANNELS13_VAL	0x3FF
#define ACTIVECHANNELS14_VAL	0x3FF

#define PROXDB_VAL		0x32
#define TOUCHSNAPDB_VAL		0x44

#define PMATITARGET_VAL		500
#define PMATIC_VAL		0

#endif
