#
#Makefile for the pinctrl dirver
#
obj-$(CONFIG_AMLOGIC_PINCTRL)	+= pinctrl-meson.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON8B) += pinctrl-meson8b.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_GXL) += pinctrl_gxl.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_AXG) += pinctrl-mesonaxg.o
obj-$(CONFIG_AMLOGIC_PINCTRL_MESON_TXLX) += pinctrl-meson-txlx.o
