obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-aes-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-tdes-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-crypto-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-sha-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_BLKMV) 				+= aml-aes-blkmv.o
obj-$(CONFIG_AMLOGIC_CRYPTO_BLKMV) 				+= aml-tdes-blkmv.o
obj-$(CONFIG_AMLOGIC_CRYPTO_BLKMV) 				+= aml-crypto-blkmv.o
