obj-$(CONFIG_AMLOGIC_CRYPTO) 				+= aml-aes-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO) 				+= aml-tdes-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO) 				+= aml-crypto-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO) 				+= aml-sha-dma.o
