#
# Makefile for Meson TL1 clk
#

obj-$(CONFIG_AMLOGIC_GX_CLK) += tl1.o tl1_ao.o	 	\
				tl1_clk_sdemmc.o 	\
				tl1_clk_media.o		\
				tl1_clk_misc.o		\
				tl1_clk_gpu.o		\
				tl1_clk-pll.o		\
				tl1_clk-mpll.o		\
