KBUILD_CFLAGS += -Wlarger-than=28792
KBUILD_CFLAGS += -Wstack-usage=1856

obj-$(CONFIG_AMLOGIC_SND_SOC)   += meson/
obj-$(CONFIG_AMLOGIC_SND_SOC)   += auge/
obj-$(CONFIG_AMLOGIC_SND_SOC)   += common/
