# AML Platform Support
snd-soc-aml-pcm-objs := aml_pcm.o
snd-soc-aml-i2s-objs := aml_i2s.o
snd-soc-aml-i2s-dai-objs := aml_i2s_dai.o
snd-soc-aml-pcm-dai-objs := aml_pcm_dai.o
snd-soc-aml-spdif-dai-objs  := aml_spdif_dai.o
snd-soc-aml-hw-objs  := aml_audio_hw.o
snd-soc-aml-hw-pcm2bt-objs  := aml_audio_hw_pcm.o
snd-soc-aml-dmic-objs	:= aml_dmic.o

obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-pcm.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-i2s.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-i2s-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-pcm-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-hw.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += aml_notify.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-hw-pcm2bt.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-spdif-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-dmic.o

# AML spdif codec support
snd-soc-aml-spdif-codec-objs := aml_spdif_codec.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-spdif-codec.o

#AML M8 Machine support
snd-soc-aml-meson-objs := aml_meson.o
obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-meson.o

#AML G9TV Machine support
snd-soc-aml-tv-objs := aml_tv.o
#obj-$(CONFIG_AMLOGIC_SND_SOC) += snd-soc-aml-tv.o
