tddi_ts-$(CONFIG_TOUCHSCREEN_TDDI) := \
	ilitek_v3.o \
	ilitek_v3_ic.o \
	ilitek_v3_touch.o \
	ilitek_v3_mp.o \
	ilitek_v3_i2c.o \
	ilitek_v3_flash.o \
	ilitek_v3_qcom.o \
	ilitek_v3_node.o
obj-$(CONFIG_TOUCHSCREEN_TDDI) += tddi_ts.o
