#
# Makefile for touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_FTS) += focaltech_touch/
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_GT1X) += goodix_gt1x/
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_GT9XX) += goodix_gt9xx/
