#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

snd-soc-mt8365-pcm-objs := \
    mt8365-afe-pcm.o mt8365-afe-utils.o mt8365-afe-controls.o mt8365-afe-debug.o

# MTK Platform Support
obj-$(CONFIG_SND_SOC_MT8365) += snd-soc-mt8365-pcm.o

# Machine support
obj-$(CONFIG_SND_SOC_MT8365_SB35) += mt8365-sb35.o
obj-$(CONFIG_SND_SOC_MT8365_EVK) += mt8365-evk.o
obj-$(CONFIG_SND_SOC_MT8365_PUMPKIN) += mt8365-pumpkin.o
