obj-$(CONFIG_MTD_NAND_GPMI_NFC) += gpmi_nfc.o
gpmi_nfc-objs += gpmi-nfc.o
obj-$(CONFIG_SOC_IMX23) += hal-mxs.o
obj-$(CONFIG_SOC_IMX28) += hal-mxs.o
obj-$(CONFIG_SOC_IMX50) += hal-mx50.o
obj-$(CONFIG_SOC_IMX6Q) += hal-mx50.o
