# SPDX-License-Identifier: GPL-2.0-only
mtk-mdp3-y += mdp_cfg_data.o mtk-mdp3-core.o mtk-mdp3-vpu.o mtk-mdp3-regs.o
mtk-mdp3-y += mdp_tile_comp.o mdp_tile_core.o mdp_tile_scaler.o
mtk-mdp3-y += mdp_alg_core.o mdp_alg_tp.o mdp_alg_tile.o
mtk-mdp3-y += mdp_alg_rdma.o mdp_alg_rsz.o mdp_alg_wrot.o
mtk-mdp3-y += mtk-mdp3-m2m.o
mtk-mdp3-y += mtk-mdp3-capture.o
mtk-mdp3-y += mtk-mdp3-comp.o mtk-mdp3-cmdq.o

obj-$(CONFIG_VIDEO_MEDIATEK_MDP3) += mtk-mdp3.o
