obj-$(CONFIG_AMLOGIC_CVBS_OUTPUT)	+= cvbs/
obj-$(CONFIG_AMLOGIC_VDAC)		+= vdac/
obj-$(CONFIG_AMLOGIC_HDMITX)		+= hdmitx/
obj-$(CONFIG_AMLOGIC_LCD)		+= lcd/
obj-$(CONFIG_AMLOGIC_BACKLIGHT)		+= backlight/
obj-$(CONFIG_AMLOGIC_VOUT_SERVE)	+= vout_serve/

