#
# Makefile for the amlogic ion device drivers.
#

#
# include driver/staging for header files
#
ccflags-y += -I$(srctree)/drivers/staging/android

amlIonDr-objs := dev_ion.o

obj-$(CONFIG_AMLOGIC_ION) += amlIonDr.o
