#
# Makefile for Tvin.
#

obj-$(CONFIG_AMLOGIC_MEDIA_TVIN) += tvin_common.o
tvin_common-objs += tvin_format_table.o
tvin_common-objs += tvin_frontend.o
tvin_common-objs += tvin_global.o

obj-$(CONFIG_AMLOGIC_MEDIA_VDIN)	+=	vdin/
obj-$(CONFIG_AMLOGIC_MEDIA_VIUIN)	+=	viu/

