#
# AMLOGIC NAND driver for mtd subsystem
#

obj-$(CONFIG_AMLOGIC_NAND) +=   aml_nand.o \
				m3_nand.o \
				aml_env.o \
				aml_dtb.o \
				aml_key.o \
				rsv_manage.o \
				nand_flash.o \
				mtd_driver.o \
				new_nand.o \
				boot.o
