# AML Platform Support
snd-soc-pcm-objs         := pcm.o
snd-soc-i2s-objs         := i2s.o
snd-soc-i2s-dai-objs     := i2s_dai.o
snd-soc-i2s2-dai-objs    := i2s2_dai.o
snd-soc-pcm-dai-objs     := pcm_dai.o
snd-soc-spdif-dai-objs   := spdif_dai.o
snd-soc-hw-objs          := audio_hw.o
snd-soc-hw-pcm2bt-objs   := audio_hw_pcm.o
snd-soc-dmic-objs	 := dmic.o
snd-soc-audio-iomap-objs := audio_iomap.o
snd-soc-spdif-codec-objs := spdif_codec.o

obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-pcm.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-i2s.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-i2s-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-i2s2-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-pcm-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-hw.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-hw-pcm2bt.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-spdif-dai.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-dmic.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-audio-iomap.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-spdif-codec.o

#AML Meson Audio Machine support
snd-soc-meson-objs := meson.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-meson.o

#AML TV Machine support
snd-soc-tv-objs := tv.o
obj-$(CONFIG_AMLOGIC_SND_SOC_MESON) += snd-soc-tv.o
