
obj-$(CONFIG_AMLOGIC_PMU)                   += aml_pmu/
obj-$(CONFIG_AMLOGIC_PMU_OF)                += aml_pmu_of_common.o

obj-$(CONFIG_AMLOGIC_M8B_DVFS)              += aml_dvfs/
obj-$(CONFIG_AMLOGIC_POWER)                 += power_ctrl.o
