
obj-$(CONFIG_AMLOGIC_TEMP_SENSOR)	+= aml_thermal_hw.o
obj-$(CONFIG_AMLOGIC_CPUCORE_THERMAL)	+= cpucore_cooling.o
obj-$(CONFIG_AMLOGIC_GPU_THERMAL)	+= gpu_cooling.o
obj-$(CONFIG_AMLOGIC_GPUCORE_THERMAL)	+= gpucore_cooling.o

