/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __PHY_MTK_MIPI_CSI_V_2_1_RX_REG_H__
#define __PHY_MTK_MIPI_CSI_V_2_1_RX_REG_H__

/*
 * mipi rx ana cdphy csi0
 */

#define CDPHY_RX_ANA_0 0x0000
#define RG_CSI0_BG_CORE_EN_SHIFT 0
#define RG_CSI0_BG_CORE_EN_MASK (0x1 << 0)
#define RG_CSI0_BG_LPF_EN_SHIFT 1
#define RG_CSI0_BG_LPF_EN_MASK (0x1 << 1)
#define RG_CSI0_EQ_PROTECT_EN_SHIFT 4
#define RG_CSI0_EQ_PROTECT_EN_MASK (0x1 << 4)
#define RG_CSI0_BYTE_CK_RSTB_SEL_SHIFT 5
#define RG_CSI0_BYTE_CK_RSTB_SEL_MASK (0x1 << 5)
#define RG_CSI0_DPHY_L0_CKSEL_SHIFT 8
#define RG_CSI0_DPHY_L0_CKSEL_MASK (0x1 << 8)
#define RG_CSI0_DPHY_L1_CKSEL_SHIFT 9
#define RG_CSI0_DPHY_L1_CKSEL_MASK (0x1 << 9)
#define RG_CSI0_DPHY_L2_CKSEL_SHIFT 10
#define RG_CSI0_DPHY_L2_CKSEL_MASK (0x1 << 10)
#define RG_CSI0_DPHY_L0_CKMODE_EN_SHIFT 12
#define RG_CSI0_DPHY_L0_CKMODE_EN_MASK (0x1 << 12)
#define RG_CSI0_DPHY_L1_CKMODE_EN_SHIFT 13
#define RG_CSI0_DPHY_L1_CKMODE_EN_MASK (0x1 << 13)
#define RG_CSI0_DPHY_L2_CKMODE_EN_SHIFT 14
#define RG_CSI0_DPHY_L2_CKMODE_EN_MASK (0x1 << 14)
#define RG_CSI0_CDPHY_L0_T0_BYTECK_INVERT_SHIFT 16
#define RG_CSI0_CDPHY_L0_T0_BYTECK_INVERT_MASK (0x1 << 16)
#define RG_CSI0_DPHY_L1_BYTECK_INVERT_SHIFT 17
#define RG_CSI0_DPHY_L1_BYTECK_INVERT_MASK (0x1 << 17)
#define RG_CSI0_CDPHY_L2_T1_BYTECK_INVERT_SHIFT 18
#define RG_CSI0_CDPHY_L2_T1_BYTECK_INVERT_MASK (0x1 << 18)
#define RG_CSI0_CPHY_EN_SHIFT 20
#define RG_CSI0_CPHY_EN_MASK (0x1 << 20)
#define RG_CSI0_CPHY_T0_CDR_FIRST_EDGE_EN_SHIFT 21
#define RG_CSI0_CPHY_T0_CDR_FIRST_EDGE_EN_MASK (0x1 << 21)
#define RG_CSI0_CPHY_T1_CDR_FIRST_EDGE_EN_SHIFT 22
#define RG_CSI0_CPHY_T1_CDR_FIRST_EDGE_EN_MASK (0x1 << 22)
#define RG_CSI0_CDPHY_L0_T0_FORCE_INIT_SHIFT 24
#define RG_CSI0_CDPHY_L0_T0_FORCE_INIT_MASK (0x1 << 24)
#define RG_CSI0_DPHY_L1_FORCE_INIT_SHIFT 25
#define RG_CSI0_DPHY_L1_FORCE_INIT_MASK (0x1 << 25)
#define RG_CSI0_CDPHY_L2_T1_FORCE_INIT_SHIFT 26
#define RG_CSI0_CDPHY_L2_T1_FORCE_INIT_MASK (0x1 << 26)
#define RG_CSI0_CDPHY_L0_T0_SYNC_INIT_CTRL_SHIFT 28
#define RG_CSI0_CDPHY_L0_T0_SYNC_INIT_CTRL_MASK (0x1 << 28)
#define RG_CSI0_DPHY_L1_SYNC_INIT_CTRL_SHIFT 29
#define RG_CSI0_DPHY_L1_SYNC_INIT_CTRL_MASK (0x1 << 29)
#define RG_CSI0_CDPHY_L2_T1_SYNC_INIT_CTRL_SHIFT 30
#define RG_CSI0_CDPHY_L2_T1_SYNC_INIT_CTRL_MASK (0x1 << 30)
#define RG_CSI0_FORCE_HSRT_EN_SHIFT 31
#define RG_CSI0_FORCE_HSRT_EN_MASK (0x1 << 31)

#define CDPHY_RX_ANA_1 0x0004
#define RG_CSI0_BG_LPRX_VTL_SEL_SHIFT 0
#define RG_CSI0_BG_LPRX_VTL_SEL_MASK (0x7 << 0)
#define RG_CSI0_BG_LPRX_VTH_SEL_SHIFT 4
#define RG_CSI0_BG_LPRX_VTH_SEL_MASK (0x7 << 4)
#define RG_CSI0_BG_VREF_SEL_SHIFT 8
#define RG_CSI0_BG_VREF_SEL_MASK (0xf << 8)
#define RG_CSI0_CDPHY_DELAYCAL_CK_SEL_SHIFT 12
#define RG_CSI0_CDPHY_DELAYCAL_CK_SEL_MASK (0x7 << 12)
#define RG_CSI0_CDPHY_EQ_DES_VREF_SEL_SHIFT 16
#define RG_CSI0_CDPHY_EQ_DES_VREF_SEL_MASK (0x7 << 16)
#define RG_CSI0_CDPHY_DELAY_VREF_SEL_SHIFT 20
#define RG_CSI0_CDPHY_DELAY_VREF_SEL_MASK (0x7 << 20)
#define RG_CSI0_DPHY_L0_DELAYCAL_EN_SHIFT 24
#define RG_CSI0_DPHY_L0_DELAYCAL_EN_MASK (0x1 << 24)
#define RG_CSI0_DPHY_L1_DELAYCAL_EN_SHIFT 25
#define RG_CSI0_DPHY_L1_DELAYCAL_EN_MASK (0x1 << 25)
#define RG_CSI0_DPHY_L2_DELAYCAL_EN_SHIFT 26
#define RG_CSI0_DPHY_L2_DELAYCAL_EN_MASK (0x1 << 26)
#define RG_CSI0_DPHY_L0_DELAYCAL_RSTB_SHIFT 28
#define RG_CSI0_DPHY_L0_DELAYCAL_RSTB_MASK (0x1 << 28)
#define RG_CSI0_DPHY_L1_DELAYCAL_RSTB_SHIFT 29
#define RG_CSI0_DPHY_L1_DELAYCAL_RSTB_MASK (0x1 << 29)
#define RG_CSI0_DPHY_L2_DELAYCAL_RSTB_SHIFT 30
#define RG_CSI0_DPHY_L2_DELAYCAL_RSTB_MASK (0x1 << 30)

#define CDPHY_RX_ANA_2 0x0008
#define RG_CSI0_L0P_T0A_HSRT_CODE_SHIFT 0
#define RG_CSI0_L0P_T0A_HSRT_CODE_MASK (0x1f << 0)
#define RG_CSI0_L0N_T0B_HSRT_CODE_SHIFT 8
#define RG_CSI0_L0N_T0B_HSRT_CODE_MASK (0x1f << 8)
#define RG_CSI0_CPHY_T0_CDR_SELF_CAL_EN_SHIFT 16
#define RG_CSI0_CPHY_T0_CDR_SELF_CAL_EN_MASK (0x1 << 16)
#define RG_CSI0_CPHY_T1_CDR_SELF_CAL_EN_SHIFT 17
#define RG_CSI0_CPHY_T1_CDR_SELF_CAL_EN_MASK (0x1 << 17)
#define RG_CSI0_BG_ALP_RX_VTH_SEL_SHIFT 24
#define RG_CSI0_BG_ALP_RX_VTH_SEL_MASK (0x7 << 24)
#define RG_CSI0_BG_ALP_RX_VTL_SEL_SHIFT 28
#define RG_CSI0_BG_ALP_RX_VTL_SEL_MASK (0x7 << 28)

#define CDPHY_RX_ANA_3 0x000c
#define RG_CSI0_L1P_T0C_HSRT_CODE_SHIFT 0
#define RG_CSI0_L1P_T0C_HSRT_CODE_MASK (0x1f << 0)
#define RG_CSI0_L1N_T1A_HSRT_CODE_SHIFT 8
#define RG_CSI0_L1N_T1A_HSRT_CODE_MASK (0x1f << 8)
#define RG_CSI0_OS_CAL_CNT_SEL_SHIFT 16
#define RG_CSI0_OS_CAL_CNT_SEL_MASK (0x3 << 16)
#define RG_CSI0_EQ_DES_VREF_SEL_SHIFT 20
#define RG_CSI0_EQ_DES_VREF_SEL_MASK (0x3f << 20)

#define CDPHY_RX_ANA_4 0x0010
#define RG_CSI0_L2P_T1B_HSRT_CODE_SHIFT 0
#define RG_CSI0_L2P_T1B_HSRT_CODE_MASK (0x1f << 0)
#define RG_CSI0_L2N_T1C_HSRT_CODE_SHIFT 8
#define RG_CSI0_L2N_T1C_HSRT_CODE_MASK (0x1f << 8)

#define CDPHY_RX_ANA_5 0x0014
#define RG_CSI0_CDPHY_EQ_BW_SHIFT 0
#define RG_CSI0_CDPHY_EQ_BW_MASK (0x3 << 0)
#define RG_CSI0_CDPHY_EQ_IS_SHIFT 2
#define RG_CSI0_CDPHY_EQ_IS_MASK (0x3 << 2)
#define RG_CSI0_CDPHY_EQ_DG0_EN_SHIFT 4
#define RG_CSI0_CDPHY_EQ_DG0_EN_MASK (0x1 << 4)
#define RG_CSI0_CDPHY_EQ_DG1_EN_SHIFT 5
#define RG_CSI0_CDPHY_EQ_DG1_EN_MASK (0x1 << 5)
#define RG_CSI0_CDPHY_EQ_LATCH_EN_SHIFT 6
#define RG_CSI0_CDPHY_EQ_LATCH_EN_MASK (0x1 << 6)
#define RG_CSI0_CDPHY_EQ_SR0_SHIFT 8
#define RG_CSI0_CDPHY_EQ_SR0_MASK (0xf << 8)
#define RG_CSI0_CDPHY_EQ_SR1_SHIFT 12
#define RG_CSI0_CDPHY_EQ_SR1_MASK (0xf << 12)
#define RG_CSI0_L0_T0AB_EQ_MON_EN_SHIFT 16
#define RG_CSI0_L0_T0AB_EQ_MON_EN_MASK (0x1 << 16)
#define RG_CSI0_L1_T1AB_EQ_MON_EN_SHIFT 17
#define RG_CSI0_L1_T1AB_EQ_MON_EN_MASK (0x1 << 17)
#define RG_CSI0_L2_T1BC_EQ_MON_EN_SHIFT 18
#define RG_CSI0_L2_T1BC_EQ_MON_EN_MASK (0x1 << 18)
#define RG_CSI0_XX_T0BC_EQ_MON_EN_SHIFT 24
#define RG_CSI0_XX_T0BC_EQ_MON_EN_MASK (0x1 << 24)
#define RG_CSI0_XX_T0CA_EQ_MON_EN_SHIFT 25
#define RG_CSI0_XX_T0CA_EQ_MON_EN_MASK (0x1 << 25)
#define RG_CSI0_XX_T1CA_EQ_MON_EN_SHIFT 26
#define RG_CSI0_XX_T1CA_EQ_MON_EN_MASK (0x1 << 26)

#define CDPHY_RX_ANA_6 0x0018
#define RG_CSI0_CPHY_T0_CDR_AB_WIDTH_SHIFT 0
#define RG_CSI0_CPHY_T0_CDR_AB_WIDTH_MASK (0x3f << 0)
#define RG_CSI0_CPHY_T0_CDR_BC_WIDTH_SHIFT 8
#define RG_CSI0_CPHY_T0_CDR_BC_WIDTH_MASK (0x3f << 8)
#define RG_CSI0_CPHY_T0_CDR_CA_WIDTH_SHIFT 16
#define RG_CSI0_CPHY_T0_CDR_CA_WIDTH_MASK (0x3f << 16)
#define RG_CSI0_CPHY_T0_CDR_CK_DELAY_SHIFT 24
#define RG_CSI0_CPHY_T0_CDR_CK_DELAY_MASK (0x3f << 24)

#define CDPHY_RX_ANA_7 0x001c
#define RG_CSI0_CPHY_T1_CDR_AB_WIDTH_SHIFT 0
#define RG_CSI0_CPHY_T1_CDR_AB_WIDTH_MASK (0x3f << 0)
#define RG_CSI0_CPHY_T1_CDR_BC_WIDTH_SHIFT 8
#define RG_CSI0_CPHY_T1_CDR_BC_WIDTH_MASK (0x3f << 8)
#define RG_CSI0_CPHY_T1_CDR_CA_WIDTH_SHIFT 16
#define RG_CSI0_CPHY_T1_CDR_CA_WIDTH_MASK (0x3f << 16)
#define RG_CSI0_CPHY_T1_CDR_CK_DELAY_SHIFT 24
#define RG_CSI0_CPHY_T1_CDR_CK_DELAY_MASK (0x3f << 24)

#define CDPHY_RX_ANA_8 0x0020
#define RGS_CSI0_CDPHY_L0_T0AB_OS_CAL_CPLT_SHIFT 0
#define RGS_CSI0_CDPHY_L0_T0AB_OS_CAL_CPLT_MASK (0x1 << 0)
#define RGS_CSI0_CDPHY_L1_T1AB_OS_CAL_CPLT_SHIFT 1
#define RGS_CSI0_CDPHY_L1_T1AB_OS_CAL_CPLT_MASK (0x1 << 1)
#define RGS_CSI0_CDPHY_L2_T1BC_OS_CAL_CPLT_SHIFT 2
#define RGS_CSI0_CDPHY_L2_T1BC_OS_CAL_CPLT_MASK (0x1 << 2)
#define RGS_CSI0_CPHY_T0BC_OS_CAL_CPLT_SHIFT 3
#define RGS_CSI0_CPHY_T0BC_OS_CAL_CPLT_MASK (0x1 << 3)
#define RGS_CSI0_CPHY_T0CA_OS_CAL_CPLT_SHIFT 4
#define RGS_CSI0_CPHY_T0CA_OS_CAL_CPLT_MASK (0x1 << 4)
#define RGS_CSI0_CPHY_T1CA_OS_CAL_CPLT_SHIFT 5
#define RGS_CSI0_CPHY_T1CA_OS_CAL_CPLT_MASK (0x1 << 5)
#define RGS_CSI0_OS_CAL_CODE_SHIFT 8
#define RGS_CSI0_OS_CAL_CODE_MASK (0xff << 8)
#define RG_CSI0_L0_T0AB_EQ_OS_CAL_EN_SHIFT 16
#define RG_CSI0_L0_T0AB_EQ_OS_CAL_EN_MASK (0x1 << 16)
#define RG_CSI0_L1_T1AB_EQ_OS_CAL_EN_SHIFT 17
#define RG_CSI0_L1_T1AB_EQ_OS_CAL_EN_MASK (0x1 << 17)
#define RG_CSI0_L2_T1BC_EQ_OS_CAL_EN_SHIFT 18
#define RG_CSI0_L2_T1BC_EQ_OS_CAL_EN_MASK (0x1 << 18)
#define RG_CSI0_XX_T0BC_EQ_OS_CAL_EN_SHIFT 19
#define RG_CSI0_XX_T0BC_EQ_OS_CAL_EN_MASK (0x1 << 19)
#define RG_CSI0_XX_T0CA_EQ_OS_CAL_EN_SHIFT 20
#define RG_CSI0_XX_T0CA_EQ_OS_CAL_EN_MASK (0x1 << 20)
#define RG_CSI0_XX_T1CA_EQ_OS_CAL_EN_SHIFT 21
#define RG_CSI0_XX_T1CA_EQ_OS_CAL_EN_MASK (0x1 << 21)
#define RG_CSI0_OS_CAL_SEL_SHIFT 24
#define RG_CSI0_OS_CAL_SEL_MASK (0x7 << 24)
#define RG_CSI0_OS_CAL_DIV_SHIFT 28
#define RG_CSI0_OS_CAL_DIV_MASK (0x7 << 28)

#define CDPHY_RX_ANA_9 0x0024
#define RGS_CSI0_CPHY_T0_DLL_CODE_SHIFT 0
#define RGS_CSI0_CPHY_T0_DLL_CODE_MASK (0xf << 0)
#define RGS_CSI0_CPHY_T0_MASK_CAL_CPLT_SHIFT 4
#define RGS_CSI0_CPHY_T0_MASK_CAL_CPLT_MASK (0x1 << 4)
#define RGS_CSI0_CPHY_T0_MASK_CAL_OF_SHIFT 5
#define RGS_CSI0_CPHY_T0_MASK_CAL_OF_MASK (0x1 << 5)
#define RGS_CSI0_CPHY_T1_DLL_CODE_SHIFT 8
#define RGS_CSI0_CPHY_T1_DLL_CODE_MASK (0xf << 8)
#define RGS_CSI0_CPHY_T1_MASK_CAL_CPLT_SHIFT 12
#define RGS_CSI0_CPHY_T1_MASK_CAL_CPLT_MASK (0x1 << 12)
#define RGS_CSI0_CPHY_T1_MASK_CAL_OF_SHIFT 13
#define RGS_CSI0_CPHY_T1_MASK_CAL_OF_MASK (0x1 << 13)
#define RG_CSI0_RESERVE_SHIFT 16
#define RG_CSI0_RESERVE_MASK (0xffff << 16)

#define CDPHY_RX_ANA_FORCE_MODE_0 0x0040
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_MASK (0x1 << 9)
#define RO_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_SHIFT 17
#define RO_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_SHIFT 20
#define RO_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_SHIFT 21
#define RO_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_SHIFT 24
#define RO_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_SHIFT 25
#define RO_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_0 0x0044
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_MASK (0x1 << 9)

#define CDPHY_RX_ANA_AD_0 0x0048
#define RO_AD_CSI0_CDPHY_L0P_T0A_LPRX_OUT_SHIFT 0
#define RO_AD_CSI0_CDPHY_L0P_T0A_LPRX_OUT_MASK (0x1 << 0)
#define RO_AD_CSI0_CDPHY_L0N_T0B_LPRX_OUT_SHIFT 1
#define RO_AD_CSI0_CDPHY_L0N_T0B_LPRX_OUT_MASK (0x1 << 1)
#define RO_AD_CSI0_CDPHY_L1P_T0C_LPRX_OUT_SHIFT 4
#define RO_AD_CSI0_CDPHY_L1P_T0C_LPRX_OUT_MASK (0x1 << 4)
#define RO_AD_CSI0_CDPHY_L1N_T1A_LPRX_OUT_SHIFT 5
#define RO_AD_CSI0_CDPHY_L1N_T1A_LPRX_OUT_MASK (0x1 << 5)
#define RO_AD_CSI0_CDPHY_L2P_T1B_LPRX_OUT_SHIFT 8
#define RO_AD_CSI0_CDPHY_L2P_T1B_LPRX_OUT_MASK (0x1 << 8)
#define RO_AD_CSI0_CDPHY_L2N_T1C_LPRX_OUT_SHIFT 9
#define RO_AD_CSI0_CDPHY_L2N_T1C_LPRX_OUT_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_1 0x0050
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_ALPRX_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_ALPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_ALPRX_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_ALPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_ALPRX_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_ALPRX_EN_MASK (0x1 << 8)
#define RO_DA_CSI0_DPHY_L0_ALPRX_EN_SHIFT 16
#define RO_DA_CSI0_DPHY_L0_ALPRX_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_DPHY_L1_ALPRX_EN_SHIFT 20
#define RO_DA_CSI0_DPHY_L1_ALPRX_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_DPHY_L2_ALPRX_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L2_ALPRX_EN_MASK (0x1 << 24)

#define CDPHY_RX_ANA_FORCE_MODE_EN_1 0x0054
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_ALPRX_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_ALPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_ALPRX_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_ALPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_ALPRX_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_ALPRX_EN_MASK (0x1 << 8)

#define CDPHY_RX_ANA_AD_1 0x0058
#define RO_AD_CSI0_DPHY_L0_ALPRX_OUT_SHIFT 0
#define RO_AD_CSI0_DPHY_L0_ALPRX_OUT_MASK (0x1 << 0)
#define RO_AD_CSI0_DPHY_L1_ALPRX_OUT_SHIFT 4
#define RO_AD_CSI0_DPHY_L1_ALPRX_OUT_MASK (0x1 << 4)
#define RO_AD_CSI0_DPHY_L2_ALPRX_OUT_SHIFT 8
#define RO_AD_CSI0_DPHY_L2_ALPRX_OUT_MASK (0x1 << 8)

#define CDPHY_RX_ANA_FORCE_MODE_2 0x0060
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_MASK (0x1 << 9)
#define RO_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_SHIFT 17
#define RO_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_SHIFT 20
#define RO_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_SHIFT 21
#define RO_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_SHIFT 24
#define RO_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_SHIFT 25
#define RO_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_2 0x0064
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_3 0x0070
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0CA_EQ_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0CA_EQ_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0BC_EQ_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0BC_EQ_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1CA_EQ_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1CA_EQ_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_MASK (0x1 << 9)
#define RO_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CPHY_T0CA_EQ_EN_SHIFT 17
#define RO_DA_CSI0_CPHY_T0CA_EQ_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CPHY_T0BC_EQ_EN_SHIFT 20
#define RO_DA_CSI0_CPHY_T0BC_EQ_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_SHIFT 21
#define RO_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_CPHY_T1CA_EQ_EN_SHIFT 24
#define RO_DA_CSI0_CPHY_T1CA_EQ_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_SHIFT 25
#define RO_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_3 0x0074
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0CA_EQ_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0CA_EQ_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0BC_EQ_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0BC_EQ_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1CA_EQ_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1CA_EQ_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_4 0x0080
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_SAMP_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_SAMP_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_CDR_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_CDR_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_SAMP_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_SAMP_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_CDR_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_CDR_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_SAMP_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_SAMP_EN_MASK (0x1 << 8)
#define RO_DA_CSI0_DPHY_L0_SAMP_EN_SHIFT 16
#define RO_DA_CSI0_DPHY_L0_SAMP_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CPHY_T0_CDR_EN_SHIFT 17
#define RO_DA_CSI0_CPHY_T0_CDR_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_DPHY_L1_SAMP_EN_SHIFT 20
#define RO_DA_CSI0_DPHY_L1_SAMP_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CPHY_T1_CDR_EN_SHIFT 21
#define RO_DA_CSI0_CPHY_T1_CDR_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_DPHY_L2_SAMP_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L2_SAMP_EN_MASK (0x1 << 24)

#define CDPHY_RX_ANA_FORCE_MODE_EN_4 0x0084
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_SAMP_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_SAMP_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_CDR_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_CDR_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_SAMP_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_SAMP_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_CDR_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_CDR_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_SAMP_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_SAMP_EN_MASK (0x1 << 8)

#define CDPHY_RX_ANA_FORCE_MODE_5 0x0090
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_EN_SHIFT 2
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_EN_MASK (0x1 << 2)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_SYNC_INIT_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_SYNC_INIT_MASK (0x1 << 9)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_SHIFT 10
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_MASK (0x1 << 10)
#define RO_DA_CSI0_CDPHY_L0_T0_DES_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0_T0_DES_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_DPHY_L1_DES_EN_SHIFT 17
#define RO_DA_CSI0_DPHY_L1_DES_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CDPHY_L2_T1_DES_EN_SHIFT 18
#define RO_DA_CSI0_CDPHY_L2_T1_DES_EN_MASK (0x1 << 18)
#define RO_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_SHIFT 24
#define RO_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L1_DES_SYNC_INIT_SHIFT 25
#define RO_DA_CSI0_DPHY_L1_DES_SYNC_INIT_MASK (0x1 << 25)
#define RO_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_SHIFT 26
#define RO_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_MASK (0x1 << 26)

#define CDPHY_RX_ANA_FORCE_MODE_EN_5 0x0094
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_EN_SHIFT 2
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_EN_MASK (0x1 << 2)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_SYNC_INIT_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_SYNC_INIT_MASK (0x1 << 9)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_SHIFT 10
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_MASK (0x1 << 10)

#define CDPHY_RX_ANA_AD_HS_0 0x00a0
#define RO_AD_CSI0_CPHY_T0CA_SHIFT 0
#define RO_AD_CSI0_CPHY_T0CA_MASK (0xff << 0)
#define RO_AD_CSI0_CPHY_T0BC_SHIFT 8
#define RO_AD_CSI0_CPHY_T0BC_MASK (0xff << 8)
#define RO_AD_CSI0_CDPHY_L0_T0AB_SHIFT 16
#define RO_AD_CSI0_CDPHY_L0_T0AB_MASK (0xff << 16)

#define CDPHY_RX_ANA_AD_HS_1 0x00a4
#define RO_AD_CSI0_DPHY_L1_SHIFT 16
#define RO_AD_CSI0_DPHY_L1_MASK (0xff << 16)

#define CDPHY_RX_ANA_AD_HS_2 0x00a8
#define RO_AD_CSI0_CPHY_T1CA_SHIFT 8
#define RO_AD_CSI0_CPHY_T1CA_MASK (0xff << 8)
#define RO_AD_CSI0_CDPHY_L2_T1BC_SHIFT 16
#define RO_AD_CSI0_CDPHY_L2_T1BC_MASK (0xff << 16)
#define RO_AD_CSI0_CPHY_T1AB_SHIFT 24
#define RO_AD_CSI0_CPHY_T1AB_MASK (0xff << 24)

#define CDPHY_RX_ANA_FORCE_MODE_6 0x00b0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_CODE_MASK (0x7f << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_APPLY_MASK (0x1 << 9)
#define RO_DA_CSI0_DPHY_L0_DELAY_CODE_SHIFT 16
#define RO_DA_CSI0_DPHY_L0_DELAY_CODE_MASK (0x7f << 16)
#define RO_DA_CSI0_DPHY_L0_DELAY_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L0_DELAY_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L0_DELAY_APPLY_SHIFT 25
#define RO_DA_CSI0_DPHY_L0_DELAY_APPLY_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_6 0x00b4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_CODE_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_APPLY_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_7 0x00c0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_CODE_MASK (0x7f << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_APPLY_MASK (0x1 << 9)
#define RO_DA_CSI0_DPHY_L1_DELAY_CODE_SHIFT 16
#define RO_DA_CSI0_DPHY_L1_DELAY_CODE_MASK (0x7f << 16)
#define RO_DA_CSI0_DPHY_L1_DELAY_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L1_DELAY_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L1_DELAY_APPLY_SHIFT 25
#define RO_DA_CSI0_DPHY_L1_DELAY_APPLY_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_7 0x00c4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_CODE_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_APPLY_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_8 0x00d0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_CODE_MASK (0x7f << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_APPLY_MASK (0x1 << 9)
#define RO_DA_CSI0_DPHY_L2_DELAY_CODE_SHIFT 16
#define RO_DA_CSI0_DPHY_L2_DELAY_CODE_MASK (0x7f << 16)
#define RO_DA_CSI0_DPHY_L2_DELAY_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L2_DELAY_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L2_DELAY_APPLY_SHIFT 25
#define RO_DA_CSI0_DPHY_L2_DELAY_APPLY_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_8 0x00d4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_CODE_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_APPLY_MASK (0x1 << 9)

#define CDPHY_RX_ANA_SETTING_0 0x00f0
#define CSR_CSI_CLK_MON_SHIFT 0
#define CSR_CSI_CLK_MON_MASK (0x1 << 0)
#define CSR_CSI_CLK_EN_SHIFT 1
#define CSR_CSI_CLK_EN_MASK (0x1 << 1)
#define CSR_ASYNC_FIFO_GATING_SEL_SHIFT 4
#define CSR_ASYNC_FIFO_GATING_SEL_MASK (0xf << 4)
#define CSR_CSI_MON_MUX_SHIFT 8
#define CSR_CSI_MON_MUX_MASK (0xff << 8)
#define CSR_CSI_RST_MODE_SHIFT 16
#define CSR_CSI_RST_MODE_MASK (0x3 << 16)
#define CSR_SW_RST_SHIFT 24
#define CSR_SW_RST_MASK (0xf << 24)

#define CDPHY_RX_ANA_SETTING_1 0x00f4
#define RG_CSI0_CDPHY_FMCK_SEL_SHIFT 0
#define RG_CSI0_CDPHY_FMCK_SEL_MASK (0x3 << 0)
#define RG_CSI0_ASYNC_OPTION_SHIFT 4
#define RG_CSI0_ASYNC_OPTION_MASK (0xf << 4)
#define RG_CAL_METHOD_3S_SHIFT 8
#define RG_CAL_METHOD_3S_MASK (0x1 << 8)
#define RG_CSI0_CDPHY_SPARE_REG_SHIFT 16
#define RG_CSI0_CDPHY_SPARE_REG_MASK (0xffff << 16)

#define CDPHY_RX_ANA_DBG_OUT 0x00f8
#define CSI_DEBUG_OUT_SHIFT 0
#define CSI_DEBUG_OUT_MASK (0xffffffff << 0)

/*
 * MIPI CSI0 CPHY
 */

#define CPHY_RX_CTRL 0x0000
#define CPHY_RX_TR0_LPRX_EN_SHIFT 0
#define CPHY_RX_TR0_LPRX_EN_MASK (0x1 << 0)
#define CPHY_RX_TR1_LPRX_EN_SHIFT 1
#define CPHY_RX_TR1_LPRX_EN_MASK (0x1 << 1)
#define CPHY_RX_TR2_LPRX_EN_SHIFT 2
#define CPHY_RX_TR2_LPRX_EN_MASK (0x1 << 2)
#define CPHY_RX_TR3_LPRX_EN_SHIFT 3
#define CPHY_RX_TR3_LPRX_EN_MASK (0x1 << 3)
#define CPHY_RX_TR0_HSRX_EN_SHIFT 4
#define CPHY_RX_TR0_HSRX_EN_MASK (0x1 << 4)
#define CPHY_RX_TR1_HSRX_EN_SHIFT 5
#define CPHY_RX_TR1_HSRX_EN_MASK (0x1 << 5)
#define CPHY_RX_TR2_HSRX_EN_SHIFT 6
#define CPHY_RX_TR2_HSRX_EN_MASK (0x1 << 6)
#define CPHY_RX_TR3_HSRX_EN_SHIFT 7
#define CPHY_RX_TR3_HSRX_EN_MASK (0x1 << 7)
#define CPHY_RX_TR0_BIST_EN_SHIFT 16
#define CPHY_RX_TR0_BIST_EN_MASK (0x1 << 16)
#define CPHY_RX_TR1_BIST_EN_SHIFT 17
#define CPHY_RX_TR1_BIST_EN_MASK (0x1 << 17)
#define CPHY_RX_TR2_BIST_EN_SHIFT 18
#define CPHY_RX_TR2_BIST_EN_MASK (0x1 << 18)
#define CPHY_RX_TR3_BIST_EN_SHIFT 19
#define CPHY_RX_TR3_BIST_EN_MASK (0x1 << 19)

#define CPHY_RX_OPT 0x0008
#define RG_CPHY_RX_PRBS_GEN_DATA_DELAY_EN_SHIFT 0
#define RG_CPHY_RX_PRBS_GEN_DATA_DELAY_EN_MASK (0x1 << 0)
#define RG_CPHY_RX_LP_MODE_SHIFT 1
#define RG_CPHY_RX_LP_MODE_MASK (0x1 << 1)
#define RG_CPHY_RX_SYNC_DETECT_OPT_SHIFT 4
#define RG_CPHY_RX_SYNC_DETECT_OPT_MASK (0x7 << 4)
#define RG_CPHY_RX_TR0_INIT_WIRE_STATE_SHIFT 16
#define RG_CPHY_RX_TR0_INIT_WIRE_STATE_MASK (0x7 << 16)
#define RG_CPHY_RX_TR1_INIT_WIRE_STATE_SHIFT 20
#define RG_CPHY_RX_TR1_INIT_WIRE_STATE_MASK (0x7 << 20)
#define RG_CPHY_RX_TR2_INIT_WIRE_STATE_SHIFT 24
#define RG_CPHY_RX_TR2_INIT_WIRE_STATE_MASK (0x7 << 24)
#define RG_CPHY_RX_TR3_INIT_WIRE_STATE_SHIFT 28
#define RG_CPHY_RX_TR3_INIT_WIRE_STATE_MASK (0x7 << 28)

#define CPHY_RX_DETECT_CTRL_SYNC 0x0010
#define RG_CPHY_RX_DETECT_7S_DIS_SYNC_SHIFT 0
#define RG_CPHY_RX_DETECT_7S_DIS_SYNC_MASK (0x1 << 0)
#define RG_CPHY_RX_DETECT_7S_MASK_SYNC_SHIFT 1
#define RG_CPHY_RX_DETECT_7S_MASK_SYNC_MASK (0x7f << 1)
#define RG_CPHY_RX_DETECT_7S_WORD_SYNC_SHIFT 8
#define RG_CPHY_RX_DETECT_7S_WORD_SYNC_MASK (0x1fffff << 8)

#define CPHY_RX_DETECT_CTRL_ESCAPE 0x0014
#define RG_CPHY_RX_DETECT_7S_DIS_ESCAPE_SHIFT 0
#define RG_CPHY_RX_DETECT_7S_DIS_ESCAPE_MASK (0x1 << 0)
#define RG_CPHY_RX_DETECT_7S_MASK_ESCAPE_SHIFT 1
#define RG_CPHY_RX_DETECT_7S_MASK_ESCAPE_MASK (0x7f << 1)
#define RG_CPHY_RX_DETECT_7S_WORD_ESCAPE_SHIFT 8
#define RG_CPHY_RX_DETECT_7S_WORD_ESCAPE_MASK (0x1fffff << 8)

#define CPHY_RX_DETECT_CTRL_POST 0x0018
#define RG_CPHY_RX_DETECT_7S_DIS_POST_SHIFT 0
#define RG_CPHY_RX_DETECT_7S_DIS_POST_MASK (0x1 << 0)
#define RG_CPHY_RX_DATA_VALID_POST_EN_SHIFT 4
#define RG_CPHY_RX_DATA_VALID_POST_EN_MASK (0x1 << 4)
#define RG_CPHY_RX_DETECT_7S_WORD_POST_SHIFT 8
#define RG_CPHY_RX_DETECT_7S_WORD_POST_MASK (0x1fffff << 8)

#define CPHY_RX_TRIO0_DEBUG_0 0x0020
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO0_DEBUG_1 0x0024
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR0_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR0_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR0_DETECT_SYNC_SHIFT 16
#define RO_CPHY_RX_TR0_DETECT_SYNC_MASK (0x1 << 16)
#define RO_CPHY_RX_TR0_DETECT_ESCAPE_SHIFT 17
#define RO_CPHY_RX_TR0_DETECT_ESCAPE_MASK (0x1 << 17)
#define RO_CPHY_RX_TR0_DETECT_POST_SHIFT 18
#define RO_CPHY_RX_TR0_DETECT_POST_MASK (0x1 << 18)
#define RO_CPHY_RX_TR0_POSITION_SYNC_SHIFT 24
#define RO_CPHY_RX_TR0_POSITION_SYNC_MASK (0xf << 24)
#define RO_CPHY_RX_TR0_POSITION_ESCAPE_SHIFT 28
#define RO_CPHY_RX_TR0_POSITION_ESCAPE_MASK (0xf << 28)

#define CPHY_RX_TRIO1_DEBUG_0 0x0030
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO1_DEBUG_1 0x0034
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR1_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR1_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR1_DETECT_SYNC_SHIFT 16
#define RO_CPHY_RX_TR1_DETECT_SYNC_MASK (0x1 << 16)
#define RO_CPHY_RX_TR1_DETECT_ESCAPE_SHIFT 17
#define RO_CPHY_RX_TR1_DETECT_ESCAPE_MASK (0x1 << 17)
#define RO_CPHY_RX_TR1_DETECT_POST_SHIFT 18
#define RO_CPHY_RX_TR1_DETECT_POST_MASK (0x1 << 18)
#define RO_CPHY_RX_TR1_POSITION_SYNC_SHIFT 24
#define RO_CPHY_RX_TR1_POSITION_SYNC_MASK (0xf << 24)
#define RO_CPHY_RX_TR1_POSITION_ESCAPE_SHIFT 28
#define RO_CPHY_RX_TR1_POSITION_ESCAPE_MASK (0xf << 28)

#define CPHY_RX_TRIO2_DEBUG_0 0x0040
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO2_DEBUG_1 0x0044
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR2_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR2_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR2_DETECT_SYNC_SHIFT 16
#define RO_CPHY_RX_TR2_DETECT_SYNC_MASK (0x1 << 16)
#define RO_CPHY_RX_TR2_DETECT_ESCAPE_SHIFT 17
#define RO_CPHY_RX_TR2_DETECT_ESCAPE_MASK (0x1 << 17)
#define RO_CPHY_RX_TR2_DETECT_POST_SHIFT 18
#define RO_CPHY_RX_TR2_DETECT_POST_MASK (0x1 << 18)
#define RO_CPHY_RX_TR2_POSITION_SYNC_SHIFT 24
#define RO_CPHY_RX_TR2_POSITION_SYNC_MASK (0xf << 24)
#define RO_CPHY_RX_TR2_POSITION_ESCAPE_SHIFT 28
#define RO_CPHY_RX_TR2_POSITION_ESCAPE_MASK (0xf << 28)

#define CPHY_RX_TRIO3_DEBUG_0 0x0050
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO3_DEBUG_1 0x0054
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR3_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR3_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR3_DETECT_SYNC_SHIFT 16
#define RO_CPHY_RX_TR3_DETECT_SYNC_MASK (0x1 << 16)
#define RO_CPHY_RX_TR3_DETECT_ESCAPE_SHIFT 17
#define RO_CPHY_RX_TR3_DETECT_ESCAPE_MASK (0x1 << 17)
#define RO_CPHY_RX_TR3_DETECT_POST_SHIFT 18
#define RO_CPHY_RX_TR3_DETECT_POST_MASK (0x1 << 18)
#define RO_CPHY_RX_TR3_POSITION_SYNC_SHIFT 24
#define RO_CPHY_RX_TR3_POSITION_SYNC_MASK (0xf << 24)
#define RO_CPHY_RX_TR3_POSITION_ESCAPE_SHIFT 28
#define RO_CPHY_RX_TR3_POSITION_ESCAPE_MASK (0xf << 28)

#define CPHY_RX_BIST_TRIO0_PROGSEQ_0 0x0060
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO0_PROGSEQ_1 0x0064
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO1_PROGSEQ_0 0x0068
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO1_PROGSEQ_1 0x006c
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO2_PROGSEQ_0 0x0070
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO2_PROGSEQ_1 0x0074
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO3_PROGSEQ_0 0x0078
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO3_PROGSEQ_1 0x007c
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO0_CTRL 0x0080
#define RG_CPHY_RX_TR0_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR0_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR0_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR0_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR0_PRBS_SEED_2_SHIFT 16
#define RG_CPHY_RX_TR0_PRBS_SEED_2_MASK (0x3 << 16)
#define RG_CPHY_RX_TR0_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR0_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR0_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR0_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR0_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR0_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR0_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR0_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_TRIO1_CTRL 0x0084
#define RG_CPHY_RX_TR1_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR1_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR1_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR1_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR1_PRBS_SEED_2_SHIFT 16
#define RG_CPHY_RX_TR1_PRBS_SEED_2_MASK (0x3 << 16)
#define RG_CPHY_RX_TR1_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR1_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR1_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR1_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR1_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR1_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR1_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR1_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_TRIO2_CTRL 0x0088
#define RG_CPHY_RX_TR2_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR2_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR2_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR2_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR2_PRBS_SEED_2_SHIFT 16
#define RG_CPHY_RX_TR2_PRBS_SEED_2_MASK (0x3 << 16)
#define RG_CPHY_RX_TR2_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR2_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR2_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR2_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR2_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR2_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR2_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR2_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_TRIO3_CTRL 0x008c
#define RG_CPHY_RX_TR3_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR3_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR3_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR3_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR3_PRBS_SEED_2_SHIFT 16
#define RG_CPHY_RX_TR3_PRBS_SEED_2_MASK (0x3 << 16)
#define RG_CPHY_RX_TR3_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR3_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR3_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR3_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR3_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR3_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR3_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR3_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_DBG_STATUS 0x0090
#define RO_CPHY_RX_TR0_BIST_LP_HS_LP_DONE_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_LP_HS_LP_DONE_MASK (0x1 << 0)
#define RO_CPHY_RX_TR1_BIST_LP_HS_LP_DONE_SHIFT 1
#define RO_CPHY_RX_TR1_BIST_LP_HS_LP_DONE_MASK (0x1 << 1)
#define RO_CPHY_RX_TR2_BIST_LP_HS_LP_DONE_SHIFT 2
#define RO_CPHY_RX_TR2_BIST_LP_HS_LP_DONE_MASK (0x1 << 2)
#define RO_CPHY_RX_TR3_BIST_LP_HS_LP_DONE_SHIFT 3
#define RO_CPHY_RX_TR3_BIST_LP_HS_LP_DONE_MASK (0x1 << 3)

#define CPHY_RX_BIST_TRIO0_STATUS_0 0x00a0
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO0_STATUS_1 0x00a4
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR0_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR0_BIST_ERR_CNT_MASK (0xff << 16)
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_OVERFLOW_SHIFT 24
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 24)

#define CPHY_RX_BIST_TRIO0_STATUS_2 0x00a8
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO0_STATUS_3 0x00ac
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_BIST_TRIO1_STATUS_0 0x00b0
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO1_STATUS_1 0x00b4
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR1_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR1_BIST_ERR_CNT_MASK (0xff << 16)
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_OVERFLOW_SHIFT 24
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 24)

#define CPHY_RX_BIST_TRIO1_STATUS_2 0x00b8
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO1_STATUS_3 0x00bc
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_BIST_TRIO2_STATUS_0 0x00c0
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO2_STATUS_1 0x00c4
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR2_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR2_BIST_ERR_CNT_MASK (0xff << 16)
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_OVERFLOW_SHIFT 24
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 24)

#define CPHY_RX_BIST_TRIO2_STATUS_2 0x00c8
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO2_STATUS_3 0x00cc
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_BIST_TRIO3_STATUS_0 0x00d0
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO3_STATUS_1 0x00d4
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR3_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR3_BIST_ERR_CNT_MASK (0xff << 16)
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_OVERFLOW_SHIFT 24
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 24)

#define CPHY_RX_BIST_TRIO3_STATUS_2 0x00d8
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO3_STATUS_3 0x00dc
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_LOOPBACK_OPT 0x00e0
#define CPHY_RX_LB_TRIGGER_SYNC_INIT_SHIFT 0
#define CPHY_RX_LB_TRIGGER_SYNC_INIT_MASK (0x1 << 0)
#define CPHY_RX_LB_RELEASE_SYNC_INIT_SHIFT 1
#define CPHY_RX_LB_RELEASE_SYNC_INIT_MASK (0x1 << 1)
#define RG_PHYD2MAC_CPHY_GEN_EN_SHIFT 8
#define RG_PHYD2MAC_CPHY_GEN_EN_MASK (0x1 << 8)
#define RG_PHYD2MAC_CPHY_GEN_MODE_SHIFT 9
#define RG_PHYD2MAC_CPHY_GEN_MODE_MASK (0x1 << 9)
#define RG_PHYD2MAC_CPHY_GEN_SEL_SHIFT 10
#define RG_PHYD2MAC_CPHY_GEN_SEL_MASK (0x1 << 10)

#define CPHY_RX_FSM_STATUS 0x00e4
#define RO_CPHY_RX_TR0_FSM_SHIFT 0
#define RO_CPHY_RX_TR0_FSM_MASK (0xff << 0)
#define RO_CPHY_RX_TR1_FSM_SHIFT 8
#define RO_CPHY_RX_TR1_FSM_MASK (0xff << 8)
#define RO_CPHY_RX_TR2_FSM_SHIFT 16
#define RO_CPHY_RX_TR2_FSM_MASK (0xff << 16)
#define RO_CPHY_RX_TR3_FSM_SHIFT 24
#define RO_CPHY_RX_TR3_FSM_MASK (0xff << 24)

#define CPHY_RX_IRQ_EN 0x00f0
#define RG_CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 0
#define RG_CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 0)
#define RG_CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 1
#define RG_CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 1)
#define RG_CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 2
#define RG_CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 2)
#define RG_CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 3
#define RG_CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 3)
#define RG_CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 4
#define RG_CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 4)
#define RG_CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 5
#define RG_CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 5)
#define RG_CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 6
#define RG_CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 6)
#define RG_CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 7
#define RG_CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 7)
#define RG_CPHY_RX_IRQ_W1C_EN_SHIFT 31
#define RG_CPHY_RX_IRQ_W1C_EN_MASK (0x1 << 31)

#define CPHY_RX_IRQ_STATUS 0x00f4
#define CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_SHIFT 0
#define CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 0)
#define CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_SHIFT 1
#define CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 1)
#define CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_SHIFT 2
#define CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 2)
#define CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_SHIFT 3
#define CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 3)
#define CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_SHIFT 4
#define CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 4)
#define CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_SHIFT 5
#define CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 5)
#define CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_SHIFT 6
#define CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 6)
#define CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_SHIFT 7
#define CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 7)

#define CPHY_RX_STATE_CHK_EN 0x0100
#define CPHY_RX_STATE_CHK_EN_TRIO0_SHIFT 0
#define CPHY_RX_STATE_CHK_EN_TRIO0_MASK (0x1 << 0)
#define CPHY_RX_STATE_CHK_EN_TRIO1_SHIFT 1
#define CPHY_RX_STATE_CHK_EN_TRIO1_MASK (0x1 << 1)
#define CPHY_RX_STATE_CHK_EN_TRIO2_SHIFT 2
#define CPHY_RX_STATE_CHK_EN_TRIO2_MASK (0x1 << 2)
#define CPHY_RX_STATE_CHK_EN_TRIO3_SHIFT 3
#define CPHY_RX_STATE_CHK_EN_TRIO3_MASK (0x1 << 3)
#define RG_ALPOUT_MASK_SHIFT 16
#define RG_ALPOUT_MASK_MASK (0xff << 16)
#define RG_ALP_POST_DET_MASK_SHIFT 24
#define RG_ALP_POST_DET_MASK_MASK (0xff << 24)

#define CPHY_RX_STATE_CHK_TIMER 0x0104
#define RG_CPHY_RX_STATE_CHK_RX_TIMER_CNT_SHIFT 0
#define RG_CPHY_RX_STATE_CHK_RX_TIMER_CNT_MASK (0xffffffff << 0)

#define CPHY_RX_STATE_CHK_STATUS_TRIO0 0x0110
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO0_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO0_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO0_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO0_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO0_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO0_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO0_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO0_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO0_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO0_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO0_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO0_MASK (0xf << 28)

#define CPHY_RX_STATE_CHK_STATUS_TRIO1 0x0114
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO1_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO1_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO1_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO1_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO1_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO1_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO1_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO1_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO1_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO1_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO1_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO1_MASK (0xf << 28)

#define CPHY_RX_STATE_CHK_STATUS_TRIO2 0x0118
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO2_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO2_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO2_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO2_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO2_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO2_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO2_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO2_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO2_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO2_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO2_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO2_MASK (0xf << 28)

#define CPHY_RX_STATE_CHK_STATUS_TRIO3 0x011c
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO3_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO3_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO3_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO3_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO3_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO3_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO3_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO3_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO3_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO3_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO3_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO3_MASK (0xf << 28)

#define CPHY_RX_CAL_ALP_CTRL 0x0130
#define RG_CPHY_CAL_EN_SHIFT 0
#define RG_CPHY_CAL_EN_MASK (0x1 << 0)
#define RG_CPHY_ALP_EN_SHIFT 1
#define RG_CPHY_ALP_EN_MASK (0x1 << 1)
#define RG_PREAMBLE_DET_SEL_SHIFT 2
#define RG_PREAMBLE_DET_SEL_MASK (0x1 << 2)
#define RG_ALP_POS_DET_SEL_SHIFT 4
#define RG_ALP_POS_DET_SEL_MASK (0x1 << 4)
#define RG_ALP_STOP_DET_EN_SHIFT 5
#define RG_ALP_STOP_DET_EN_MASK (0x1 << 5)
#define RG_ALPOUT_MASK_ALP_SHIFT 6
#define RG_ALPOUT_MASK_ALP_MASK (0x1 << 6)
#define RG_ALPRX_EN_SEL_SHIFT 7
#define RG_ALPRX_EN_SEL_MASK (0x1 << 7)
#define RG_CPHY_SELCAL_PARAMETER_SHIFT 8
#define RG_CPHY_SELCAL_PARAMETER_MASK (0xff << 8)
#define RG_CPHY_ALP_SETTLE_PARAMETER_SHIFT 16
#define RG_CPHY_ALP_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_TR_PREAMBLE_DET_CNT_SHIFT 24
#define RG_TR_PREAMBLE_DET_CNT_MASK (0xff << 24)

#define CPHY_RX_INIT 0x0134
#define RG_CSI2_TINIT_CNT_SHIFT 0
#define RG_CSI2_TINIT_CNT_MASK (0xfffff << 0)
#define RG_CSI2_TINIT_CNT_EN_SHIFT 31
#define RG_CSI2_TINIT_CNT_EN_MASK (0x1 << 31)

/*
 * MIPI CSI0 DPHY
 */

#define DPHY_RX_LANE_EN 0x0000
#define DPHY_RX_LC0_EN_SHIFT 0
#define DPHY_RX_LC0_EN_MASK (0x1 << 0)
#define DPHY_RX_LC1_EN_SHIFT 1
#define DPHY_RX_LC1_EN_MASK (0x1 << 1)
#define DPHY_RX_LD0_EN_SHIFT 8
#define DPHY_RX_LD0_EN_MASK (0x1 << 8)
#define DPHY_RX_LD1_EN_SHIFT 9
#define DPHY_RX_LD1_EN_MASK (0x1 << 9)
#define DPHY_RX_LD2_EN_SHIFT 10
#define DPHY_RX_LD2_EN_MASK (0x1 << 10)
#define DPHY_RX_LD3_EN_SHIFT 11
#define DPHY_RX_LD3_EN_MASK (0x1 << 11)
#define DPHY_RX_SW_RST_SHIFT 31
#define DPHY_RX_SW_RST_MASK (0x1 << 31)

#define DPHY_RX_LANE_SELECT 0x0004
#define RG_DPHY_RX_LC0_SEL_SHIFT 0
#define RG_DPHY_RX_LC0_SEL_MASK (0x7 << 0)
#define RG_DPHY_RX_LC1_SEL_SHIFT 4
#define RG_DPHY_RX_LC1_SEL_MASK (0x7 << 4)
#define RG_DPHY_RX_LD0_SEL_SHIFT 8
#define RG_DPHY_RX_LD0_SEL_MASK (0x7 << 8)
#define RG_DPHY_RX_LD1_SEL_SHIFT 12
#define RG_DPHY_RX_LD1_SEL_MASK (0x7 << 12)
#define RG_DPHY_RX_LD2_SEL_SHIFT 16
#define RG_DPHY_RX_LD2_SEL_MASK (0x7 << 16)
#define RG_DPHY_RX_LD3_SEL_SHIFT 20
#define RG_DPHY_RX_LD3_SEL_MASK (0x7 << 20)
#define DPHY_RX_CK_DATA_MUX_EN_SHIFT 31
#define DPHY_RX_CK_DATA_MUX_EN_MASK (0x1 << 31)

#define DPHY_RX_HS_RX_EN_SW 0x0008
#define RG_DPHY_RX_LC0_HSRX_EN_SW_SHIFT 0
#define RG_DPHY_RX_LC0_HSRX_EN_SW_MASK (0x1 << 0)
#define RG_DPHY_RX_LC1_HSRX_EN_SW_SHIFT 1
#define RG_DPHY_RX_LC1_HSRX_EN_SW_MASK (0x1 << 1)
#define RG_CDPHY_RX_LD0_TRIO0_HSRX_EN_SW_SHIFT 8
#define RG_CDPHY_RX_LD0_TRIO0_HSRX_EN_SW_MASK (0x1 << 8)
#define RG_CDPHY_RX_LD1_TRIO1_HSRX_EN_SW_SHIFT 9
#define RG_CDPHY_RX_LD1_TRIO1_HSRX_EN_SW_MASK (0x1 << 9)
#define RG_CDPHY_RX_LD2_TRIO2_HSRX_EN_SW_SHIFT 10
#define RG_CDPHY_RX_LD2_TRIO2_HSRX_EN_SW_MASK (0x1 << 10)
#define RG_CDPHY_RX_LD2_TRIO3_HSRX_EN_SW_SHIFT 11
#define RG_CDPHY_RX_LD2_TRIO3_HSRX_EN_SW_MASK (0x1 << 11)

#define DPHY_RX_CLOCK_LANE0_HS_PARAMETER 0x0010
#define RG_DPHY_RX_LC0_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_DPHY_RX_LC0_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LC0_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_DPHY_RX_LC0_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_DPHY_RX_LC0_HS_PREPARE_EN_SHIFT 28
#define RG_DPHY_RX_LC0_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LC0_HS_OPTION_SHIFT 30
#define RG_DPHY_RX_LC0_HS_OPTION_MASK (0x1 << 30)

#define DPHY_RX_CLOCK_LANE1_HS_PARAMETER 0x0014
#define RG_DPHY_RX_LC1_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_DPHY_RX_LC1_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LC1_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_DPHY_RX_LC1_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_DPHY_RX_LC1_HS_PREPARE_EN_SHIFT 28
#define RG_DPHY_RX_LC1_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LC1_HS_OPTION_SHIFT 30
#define RG_DPHY_RX_LC1_HS_OPTION_MASK (0x1 << 30)

#define DPHY_RX_DATA_LANE0_HS_PARAMETER 0x0020
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LD0_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_DPHY_RX_LD0_HS_TRAIL_PARAMETER_MASK (0xff << 8)
#define RG_CDPHY_RX_LD0_TRIO0_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_CDPHY_RX_LD0_TRIO0_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LD0_HS_TRAIL_EN_SHIFT 29
#define RG_DPHY_RX_LD0_HS_TRAIL_EN_MASK (0x1 << 29)

#define DPHY_RX_DATA_LANE1_HS_PARAMETER 0x0024
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LD1_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_DPHY_RX_LD1_HS_TRAIL_PARAMETER_MASK (0xff << 8)
#define RG_CDPHY_RX_LD1_TRIO1_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_CDPHY_RX_LD1_TRIO1_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LD1_HS_TRAIL_EN_SHIFT 29
#define RG_DPHY_RX_LD1_HS_TRAIL_EN_MASK (0x1 << 29)

#define DPHY_RX_DATA_LANE2_HS_PARAMETER 0x0028
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LD2_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_DPHY_RX_LD2_HS_TRAIL_PARAMETER_MASK (0xff << 8)
#define RG_CDPHY_RX_LD2_TRIO2_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_CDPHY_RX_LD2_TRIO2_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LD2_HS_TRAIL_EN_SHIFT 29
#define RG_DPHY_RX_LD2_HS_TRAIL_EN_MASK (0x1 << 29)

#define DPHY_RX_DATA_LANE3_HS_PARAMETER 0x002c
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LD3_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_DPHY_RX_LD3_HS_TRAIL_PARAMETER_MASK (0xff << 8)
#define RG_CDPHY_RX_LD3_TRIO3_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_CDPHY_RX_LD3_TRIO3_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LD3_HS_TRAIL_EN_SHIFT 29
#define RG_DPHY_RX_LD3_HS_TRAIL_EN_MASK (0x1 << 29)

#define DPHY_RX_CLOCK_LANE_FSM 0x0030
#define RO_DPHY_RX_CL0_FSM_SHIFT 0
#define RO_DPHY_RX_CL0_FSM_MASK (0x3f << 0)
#define RO_DPHY_RX_CL1_FSM_SHIFT 8
#define RO_DPHY_RX_CL1_FSM_MASK (0x3f << 8)

#define DPHY_RX_DATA_LANE_FSM 0x0034
#define RO_DPHY_RX_DL0_FSM_SHIFT 0
#define RO_DPHY_RX_DL0_FSM_MASK (0xff << 0)
#define RO_DPHY_RX_DL1_FSM_SHIFT 8
#define RO_DPHY_RX_DL1_FSM_MASK (0xff << 8)
#define RO_DPHY_RX_DL2_FSM_SHIFT 16
#define RO_DPHY_RX_DL2_FSM_MASK (0xff << 16)
#define RO_DPHY_RX_DL3_FSM_SHIFT 24
#define RO_DPHY_RX_DL3_FSM_MASK (0xff << 24)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_NORMAL 0x0040
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_NORM_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_NORM_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_NORM_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_NORM_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_DESKEW 0x0044
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_DESKEW_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_DESKEW_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_DESKEW_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_DESKEW_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_ALTCAL 0x0048
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_ALT_CAL_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_ALT_CAL_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_ALT_CAL_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_ALT_CAL_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_PRESEQ 0x004c
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_PRE_SEQ_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_PRE_SEQ_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_PRE_SEQ_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_PRE_SEQ_MASK (0xffff << 16)

#define DPHY_RX_DESKEW_CTRL 0x0050
#define RG_DPHY_RX_DESKEW_INITIAL_SETUP_SHIFT 0
#define RG_DPHY_RX_DESKEW_INITIAL_SETUP_MASK (0xf << 0)
#define RG_DPHY_RX_DESKEW_OFFSET_SHIFT 4
#define RG_DPHY_RX_DESKEW_OFFSET_MASK (0xf << 4)
#define RG_DPHY_RX_DESKEW_EN_SHIFT 8
#define RG_DPHY_RX_DESKEW_EN_MASK (0x1 << 8)
#define RG_DPHY_RX_DESKEW_CODE_UNIT_SEL_SHIFT 9
#define RG_DPHY_RX_DESKEW_CODE_UNIT_SEL_MASK (0x1 << 9)
#define RG_DPHY_RX_DESKEW_HW_DELAY_APPLY_OPT_SHIFT 10
#define RG_DPHY_RX_DESKEW_HW_DELAY_APPLY_OPT_MASK (0x1 << 10)
#define RG_DPHY_RX_DESKEW_ACC_MODE_SHIFT 12
#define RG_DPHY_RX_DESKEW_ACC_MODE_MASK (0xf << 12)
#define RG_DPHY_RX_DESKEW_APPLY_MODE_SHIFT 16
#define RG_DPHY_RX_DESKEW_APPLY_MODE_MASK (0xf << 16)
#define RG_DPHY_RX_DESKEW_LENGTH_SHIFT 24
#define RG_DPHY_RX_DESKEW_LENGTH_MASK (0x3f << 24)
#define DPHY_RX_DESKEW_SW_RST_SHIFT 31
#define DPHY_RX_DESKEW_SW_RST_MASK (0x1 << 31)

#define DPHY_RX_DESKEW_TIMING_CTRL 0x0054
#define RG_DPHY_RX_DESKEW_SETUP_CNT_SHIFT 0
#define RG_DPHY_RX_DESKEW_SETUP_CNT_MASK (0xf << 0)
#define RG_DPHY_RX_DESKEW_HOLD_CNT_SHIFT 8
#define RG_DPHY_RX_DESKEW_HOLD_CNT_MASK (0xf << 8)
#define RG_DPHY_RX_DESKEW_DETECT_CNT_SHIFT 16
#define RG_DPHY_RX_DESKEW_DETECT_CNT_MASK (0x7f << 16)
#define RG_DPHY_RX_DESKEW_CMPLENGTH_SHIFT 24
#define RG_DPHY_RX_DESKEW_CMPLENGTH_MASK (0xf << 24)

#define DPHY_RX_DESKEW_LANE_SWAP 0x0058
#define RG_DPHY_RX_DESKEW_LANE0_SWAP_SHIFT 0
#define RG_DPHY_RX_DESKEW_LANE0_SWAP_MASK (0x3 << 0)
#define RG_DPHY_RX_DESKEW_LANE1_SWAP_SHIFT 2
#define RG_DPHY_RX_DESKEW_LANE1_SWAP_MASK (0x3 << 2)
#define RG_DPHY_RX_DESKEW_LANE2_SWAP_SHIFT 4
#define RG_DPHY_RX_DESKEW_LANE2_SWAP_MASK (0x3 << 4)
#define RG_DPHY_RX_DESKEW_LANE3_SWAP_SHIFT 6
#define RG_DPHY_RX_DESKEW_LANE3_SWAP_MASK (0x3 << 6)
#define RG_MIN_CODE_SHIFT 24
#define RG_MIN_CODE_MASK (0x7 << 24)
#define RG_MIN_CODE_EN_SHIFT 28
#define RG_MIN_CODE_EN_MASK (0x1 << 28)
#define RG_DBG_CLR_SHIFT 29
#define RG_DBG_CLR_MASK (0x1 << 29)
#define RG_APPLY_ONLY_1ST_PAT_SHIFT 30
#define RG_APPLY_ONLY_1ST_PAT_MASK (0x1 << 30)
#define RG_DBGST_OPT_SHIFT 31
#define RG_DBGST_OPT_MASK (0x1 << 31)

#define DPHY_RX_DESKEW_LANE0_CTRL 0x0060
#define DPHY_RX_DESKEW_L0_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L0_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L0_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L0_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L0_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L0_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_MASK (0x1 << 16)
#define RG_PERIODIC_DESKEW_1DIR_ONLY_SHIFT 17
#define RG_PERIODIC_DESKEW_1DIR_ONLY_MASK (0x1 << 17)
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE1_CTRL 0x0064
#define DPHY_RX_DESKEW_L1_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L1_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L1_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L1_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L1_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L1_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE2_CTRL 0x0068
#define DPHY_RX_DESKEW_L2_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L2_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L2_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L2_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L2_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L2_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE3_CTRL 0x006c
#define DPHY_RX_DESKEW_L3_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L3_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L3_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L3_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L3_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L3_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE0_DA_READ 0x0070
#define RO_DA_DPHY_L0_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L0_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L0_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L0_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L0_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L0_DELAY_CODE_MASK (0x7f << 8)

#define DPHY_RX_DESKEW_LANE1_DA_READ 0x0074
#define RO_DA_DPHY_L1_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L1_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L1_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L1_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L0_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L0_DELAY_CODE_MASK (0x7f << 8)

#define DPHY_RX_DESKEW_LANE2_DA_READ 0x0078
#define RO_DA_DPHY_L2_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L2_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L2_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L2_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L0_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L0_DELAY_CODE_MASK (0x7f << 8)

#define DPHY_RX_DESKEW_LANE3_DA_READ 0x007c
#define RO_DA_DPHY_L3_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L3_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L3_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L3_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L0_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L0_DELAY_CODE_MASK (0x7f << 8)

#define DPHY_RX_DESKEW_IRQ_EN 0x0080
#define RG_DPHY_RX_DESKEW_IRQ_EN_SHIFT 0
#define RG_DPHY_RX_DESKEW_IRQ_EN_MASK (0xffff << 0)
#define RG_DPHY_RX_DESKEW_IRQ_W1C_EN_SHIFT 31
#define RG_DPHY_RX_DESKEW_IRQ_W1C_EN_MASK (0x1 << 31)

#define DPHY_RX_DESKEW_IRQ_STATUS 0x0084
#define RO_DPHY_RX_DESKEW_IRQ_STATUS_SHIFT 0
#define RO_DPHY_RX_DESKEW_IRQ_STATUS_MASK (0xffff << 0)

#define DPHY_RX_IRQ_EN 0x0088
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_EN_SHIFT 0
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_EN_SHIFT 1
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_EN_MASK (0x1 << 1)
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_EN_SHIFT 2
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_EN_MASK (0x1 << 2)
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_EN_SHIFT 3
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_EN_MASK (0x1 << 3)
#define RG_DPHY_RX_IRQ_W1C_EN_SHIFT 31
#define RG_DPHY_RX_IRQ_W1C_EN_MASK (0x1 << 31)

#define DPHY_RX_IRQ_STATUS 0x008c
#define DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_SHIFT 0
#define DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_MASK (0x1 << 0)
#define DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_SHIFT 1
#define DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_MASK (0x1 << 1)
#define DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_SHIFT 2
#define DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_MASK (0x1 << 2)
#define DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_SHIFT 3
#define DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_MASK (0x1 << 3)

#define DPHY_RX_STATUS_0 0x00a0
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_NORM_SHIFT 0
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_NORM_MASK (0xf << 0)
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_NORM_SHIFT 4
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_NORM_MASK (0xf << 4)
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_NORM_SHIFT 8
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_NORM_MASK (0xf << 8)
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_NORM_SHIFT 12
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_NORM_MASK (0xf << 12)
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_DESKEW_SHIFT 16
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_DESKEW_MASK (0xf << 16)
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_DESKEW_SHIFT 20
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_DESKEW_MASK (0xf << 20)
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_DESKEW_SHIFT 24
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_DESKEW_MASK (0xf << 24)
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_DESKEW_SHIFT 28
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_DESKEW_MASK (0xf << 28)

#define DPHY_RX_DESKEW_DBG_MUX 0x00e0
#define RG_DPHY_RX_DESKEW_DBG_MUX_SHIFT 0
#define RG_DPHY_RX_DESKEW_DBG_MUX_MASK (0xff << 0)

#define DPHY_RX_DESKEW_OUT 0x00e4
#define RG_DPHY_RX_DESKEW_DBG_OUT_SHIFT 0
#define RG_DPHY_RX_DESKEW_DBG_OUT_MASK (0xffffffff << 0)

#define DPHY_RX_SPARE0 0x00f0
#define RG_DPHY_RX_SPARE0_SHIFT 0
#define RG_DPHY_RX_SPARE0_MASK (0x3f << 0)
#define RG_POST_CNT_SHIFT 6
#define RG_POST_CNT_MASK (0x3f << 6)
#define RG_DPHY_RX_SPARE0_2_SHIFT 12
#define RG_DPHY_RX_SPARE0_2_MASK (0xfffff << 12)

#define DPHY_RX_SPARE1 0x00f4
#define RG_DPHY_RX_SPARE1_SHIFT 0
#define RG_DPHY_RX_SPARE1_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_ENABLE 0x0100
#define DPHY_RX_BIST_EN_LANE0_SHIFT 0
#define DPHY_RX_BIST_EN_LANE0_MASK (0x1 << 0)
#define DPHY_RX_BIST_EN_LANE1_SHIFT 1
#define DPHY_RX_BIST_EN_LANE1_MASK (0x1 << 1)
#define DPHY_RX_BIST_EN_LANE2_SHIFT 2
#define DPHY_RX_BIST_EN_LANE2_MASK (0x1 << 2)
#define DPHY_RX_BIST_EN_LANE3_SHIFT 3
#define DPHY_RX_BIST_EN_LANE3_MASK (0x1 << 3)
#define RG_PHY2MAC_CDPHY_GEN_EN_SHIFT 8
#define RG_PHY2MAC_CDPHY_GEN_EN_MASK (0x1 << 8)
#define RG_PHY2MAC_CDPHY_GEN_MODE_SHIFT 9
#define RG_PHY2MAC_CDPHY_GEN_MODE_MASK (0x1 << 9)
#define RG_PHY2MAC_CDPHY_GEN_SEL_SHIFT 10
#define RG_PHY2MAC_CDPHY_GEN_SEL_MASK (0x1 << 10)

#define DPHY_RX_BIST_STATUS 0x0104
#define RO_DPHY_RX_BIST_OK_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_OK_LANE0_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_OK_LANE1_SHIFT 1
#define RO_DPHY_RX_BIST_OK_LANE1_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_OK_LANE2_SHIFT 2
#define RO_DPHY_RX_BIST_OK_LANE2_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_OK_LANE3_SHIFT 3
#define RO_DPHY_RX_BIST_OK_LANE3_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE0_SHIFT 8
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE0_MASK (0x1 << 8)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE1_SHIFT 9
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE1_MASK (0x1 << 9)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE2_SHIFT 10
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE2_MASK (0x1 << 10)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE3_SHIFT 11
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE3_MASK (0x1 << 11)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE0_SHIFT 16
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE0_MASK (0x1 << 16)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE1_SHIFT 17
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE1_MASK (0x1 << 17)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE2_SHIFT 18
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE2_MASK (0x1 << 18)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE3_SHIFT 19
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE3_MASK (0x1 << 19)

#define DPHY_RX_BIST_CONFIG_0_LANE0 0x0110
#define RG_DPHY_RX_BIST_MODE_LANE0_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE0_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE0_SHIFT 4
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE0_MASK (0x1 << 4)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE0_SHIFT 5
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE0_MASK (0x1 << 5)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE0_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE0_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_MASK (0x7fff << 16)

#define DPHY_RX_BIST_CONFIG_1_LANE0 0x0114
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE0_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE0_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE0_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE0_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE0_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE0_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE0_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE0_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE0_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE0_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE0_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE0_MASK (0x7 << 16)

#define DPHY_RX_BIST_STATUS_LANE0 0x0118
#define RO_DPHY_RX_BIST_START_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE0_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE0_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE0_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE0_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE0_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE0_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE0_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE0_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE0_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE0_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE0_MASK (0x3 << 12)

#define DPHY_RX_BIST_CONFIG_0_LANE1 0x0120
#define RG_DPHY_RX_BIST_MODE_LANE1_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE1_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE1_SHIFT 4
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE1_MASK (0x1 << 4)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE1_SHIFT 5
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE1_MASK (0x1 << 5)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE1_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE1_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_MASK (0x7fff << 16)

#define DPHY_RX_BIST_CONFIG_1_LANE1 0x0124
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE1_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE1_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE1_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE1_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE1_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE1_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE1_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE1_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE1_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE1_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE1_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE1_MASK (0x7 << 16)

#define DPHY_RX_BIST_STATUS_LANE1 0x0128
#define RO_DPHY_RX_BIST_START_LANE1_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE1_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE1_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE1_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE1_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE1_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE1_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE1_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE1_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE1_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE1_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE1_MASK (0x3 << 12)

#define DPHY_RX_BIST_CONFIG_0_LANE2 0x0130
#define RG_DPHY_RX_BIST_MODE_LANE2_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE2_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE2_SHIFT 4
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE2_MASK (0x1 << 4)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE2_SHIFT 5
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE2_MASK (0x1 << 5)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE2_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE2_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_MASK (0x7fff << 16)

#define DPHY_RX_BIST_CONFIG_1_LANE2 0x0134
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE2_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE2_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE2_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE2_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE2_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE2_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE2_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE2_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE2_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE2_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE2_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE2_MASK (0x7 << 16)

#define DPHY_RX_BIST_STATUS_LANE2 0x0138
#define RO_DPHY_RX_BIST_START_LANE2_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE2_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE2_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE2_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE2_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE2_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE2_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE2_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE2_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE2_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE2_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE2_MASK (0x3 << 12)

#define DPHY_RX_BIST_CONFIG_0_LANE3 0x0140
#define RG_DPHY_RX_BIST_MODE_LANE3_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE3_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE3_SHIFT 4
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE3_MASK (0x1 << 4)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE3_SHIFT 5
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE3_MASK (0x1 << 5)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE3_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE3_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_MASK (0x7fff << 16)

#define DPHY_RX_BIST_CONFIG_1_LANE3 0x0144
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE3_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE3_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE3_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE3_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE3_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE3_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE3_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE3_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE3_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE3_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE3_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE3_MASK (0x7 << 16)

#define DPHY_RX_BIST_STATUS_LANE3 0x0148
#define RO_DPHY_RX_BIST_START_LANE3_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE3_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE3_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE3_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE3_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE3_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE3_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE3_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE3_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE3_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE3_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE3_MASK (0x3 << 12)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE0 0x0150
#define RO_DPHY_RX_BIST_WORD_CNT_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE0 0x0154
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE0_MASK (0xffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE1 0x0158
#define RO_DPHY_RX_BIST_WORD_CNT_LANE1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE1 0x015c
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE1_MASK (0xffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE2 0x0160
#define RO_DPHY_RX_BIST_WORD_CNT_LANE2_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE2 0x0164
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE2_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE2_MASK (0xffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE3 0x0168
#define RO_DPHY_RX_BIST_WORD_CNT_LANE3_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE3 0x016c
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE3_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE3_MASK (0xffff << 0)

#define DPHY_DPHYV21_CTRL 0x0180
#define RG_DPHY_CAL_EN_SHIFT 0
#define RG_DPHY_CAL_EN_MASK (0x1 << 0)
#define RG_DPHY_PREAMBLE_EN_SHIFT 1
#define RG_DPHY_PREAMBLE_EN_MASK (0x1 << 1)
#define RG_HSIDLE_EN_SHIFT 2
#define RG_HSIDLE_EN_MASK (0x1 << 2)

#define DPHY_PRBS_SEED 0x0184
#define CSR_RLRN_PRBS_SEED_SHIFT 0
#define CSR_RLRN_PRBS_SEED_MASK (0x3ffff << 0)

#define DPHY_HS_IDLE_CNT 0x0188
#define RG_CK_DET_BYTE_CK_DIV_SHIFT 0
#define RG_CK_DET_BYTE_CK_DIV_MASK (0xff << 0)
#define RG_CK_DET_CK_CNT_SHIFT 8
#define RG_CK_DET_CK_CNT_MASK (0xff << 8)
#define RG_HSRC_EN_MASK_CNT_SHIFT 16
#define RG_HSRC_EN_MASK_CNT_MASK (0x3f << 16)
#define RG_DIV_CK_DET_SEL_SHIFT 24
#define RG_DIV_CK_DET_SEL_MASK (0x1 << 24)

#define DPHY_DFT_CLR 0x018c
#define RG_DPHY_LP00_2_SYNC_CODE_CLR_SHIFT 0
#define RG_DPHY_LP00_2_SYNC_CODE_CLR_MASK (0x1 << 0)
#define RG_DPHY_ERROR_CMP_CLR_LANE0_SHIFT 1
#define RG_DPHY_ERROR_CMP_CLR_LANE0_MASK (0x1 << 1)
#define RG_DPHY_ERROR_CMP_CLR_LANE1_SHIFT 2
#define RG_DPHY_ERROR_CMP_CLR_LANE1_MASK (0x1 << 2)
#define RG_DPHY_ERROR_CMP_CLR_LANE2_SHIFT 3
#define RG_DPHY_ERROR_CMP_CLR_LANE2_MASK (0x1 << 3)
#define RG_DPHY_ERROR_CMP_CLR_LANE3_SHIFT 4
#define RG_DPHY_ERROR_CMP_CLR_LANE3_MASK (0x1 << 4)

#define DPHY_ALT_CAL_CTRL_LANE0 0x0190
#define RG_ALT_CAL_MODE_LANE0_SHIFT 0
#define RG_ALT_CAL_MODE_LANE0_MASK (0x1f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE0 0x0194
#define RG_ALT_CAL_WORD_CNT0_LANE0_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE0_MASK (0xffff << 0)
#define DPHY_ALT_CAL_WORD_CNT0_LANE0_RO_ALT_CAL_ERR_CNT_LANE0_SHIFT 16
#define DPHY_ALT_CAL_WORD_CNT0_LANE0_RO_ALT_CAL_ERR_CNT_LANE0_MASK (0xffff << 16)

#define DPHY_ALT_CAL_WORD_CNT1_LANE0 0x0198
#define RG_ALT_CAL_WORD_CNT1_LANE0_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE0 0x019c
#define RO_ALT_CAL_ERR_CNT1_LANE0_SHIFT 0
#define RO_ALT_CAL_ERR_CNT1_LANE0_MASK (0xffffffff << 0)
#define DPHY_ALT_CAL_ERR_CNT_LANE0_RO_ALT_CAL_ERR_CNT_LANE0_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE0_RO_ALT_CAL_ERR_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_CTRL_LANE1 0x01a0
#define RG_ALT_CAL_MODE_LANE1_SHIFT 0
#define RG_ALT_CAL_MODE_LANE1_MASK (0x1f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE1 0x01a4
#define RG_ALT_CAL_WORD_CNT0_LANE1_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE1_MASK (0xffff << 0)
#define DPHY_ALT_CAL_WORD_CNT0_LANE1_RO_ALT_CAL_ERR_CNT_LANE1_SHIFT 16
#define DPHY_ALT_CAL_WORD_CNT0_LANE1_RO_ALT_CAL_ERR_CNT_LANE1_MASK (0xffff << 16)

#define DPHY_ALT_CAL_WORD_CNT1_LANE1 0x01a8
#define RG_ALT_CAL_WORD_CNT1_LANE1_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE1 0x01ac
#define DPHY_ALT_CAL_ERR_CNT_LANE1_RO_ALT_CAL_ERR_CNT_LANE1_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE1_RO_ALT_CAL_ERR_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_CTRL_LANE2 0x01b0
#define RG_ALT_CAL_MODE_LANE2_SHIFT 0
#define RG_ALT_CAL_MODE_LANE2_MASK (0x1f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE2 0x01b4
#define RG_ALT_CAL_WORD_CNT0_LANE2_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE2_MASK (0xffff << 0)
#define DPHY_ALT_CAL_WORD_CNT0_LANE2_RO_ALT_CAL_ERR_CNT_LANE2_SHIFT 16
#define DPHY_ALT_CAL_WORD_CNT0_LANE2_RO_ALT_CAL_ERR_CNT_LANE2_MASK (0xffff << 16)

#define DPHY_ALT_CAL_WORD_CNT1_LANE2 0x01b8
#define RG_ALT_CAL_WORD_CNT1_LANE2_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE2 0x01bc
#define DPHY_ALT_CAL_ERR_CNT_LANE2_RO_ALT_CAL_ERR_CNT_LANE2_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE2_RO_ALT_CAL_ERR_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_CTRL_LANE3 0x01c0
#define RG_ALT_CAL_MODE_LANE3_SHIFT 0
#define RG_ALT_CAL_MODE_LANE3_MASK (0x1f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE3 0x01c4
#define RG_ALT_CAL_WORD_CNT0_LANE3_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE3_MASK (0xffff << 0)
#define DPHY_ALT_CAL_WORD_CNT0_LANE3_RO_ALT_CAL_ERR_CNT_LANE3_SHIFT 16
#define DPHY_ALT_CAL_WORD_CNT0_LANE3_RO_ALT_CAL_ERR_CNT_LANE3_MASK (0xffff << 16)

#define DPHY_ALT_CAL_WORD_CNT1_LANE3 0x01c8
#define RG_ALT_CAL_WORD_CNT1_LANE3_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE3 0x01cc
#define DPHY_ALT_CAL_ERR_CNT_LANE3_RO_ALT_CAL_ERR_CNT_LANE3_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE3_RO_ALT_CAL_ERR_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE0 0x01d0
#define RG_DPHY_PRBS_BURST_CNT_LANE0_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE0 0x01d4
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE0_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE1 0x01d8
#define RG_DPHY_PRBS_BURST_CNT_LANE1_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE1 0x01dc
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE1_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE2 0x01e0
#define RG_DPHY_PRBS_BURST_CNT_LANE2_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE2 0x01e4
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE2_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE3 0x01e8
#define RG_DPHY_PRBS_BURST_CNT_LANE3_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE3 0x01ec
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE3_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_PKT_CNT0 0x01f0
#define RG_ALT_CAL_PKT_CNT0_SHIFT 0
#define RG_ALT_CAL_PKT_CNT0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_PKT_CNT1 0x01f4
#define RG_ALT_CAL_PKT_CNT1_SHIFT 0
#define RG_ALT_CAL_PKT_CNT1_MASK (0xffff << 0)
#define DPHY_RX_STATE_CHK_EN 0x0260

#define DPHY_RX_STATE_CHK_EN_LANE0_SHIFT 0
#define DPHY_RX_STATE_CHK_EN_LANE0_MASK (0x1 << 0)
#define DPHY_RX_STATE_CHK_EN_LANE1_SHIFT 1
#define DPHY_RX_STATE_CHK_EN_LANE1_MASK (0x1 << 1)
#define DPHY_RX_STATE_CHK_EN_LANE2_SHIFT 2
#define DPHY_RX_STATE_CHK_EN_LANE2_MASK (0x1 << 2)
#define DPHY_RX_STATE_CHK_EN_LANE3_SHIFT 3
#define DPHY_RX_STATE_CHK_EN_LANE3_MASK (0x1 << 3)

#define DPHY_RX_STATE_CHK_TIMER 0x0264
#define RG_DPHY_RX_STATE_CHK_RX_TIMER_CNT_SHIFT 0
#define RG_DPHY_RX_STATE_CHK_RX_TIMER_CNT_MASK (0xffffffff << 0)

#define DPHY_RX_STATE_CHK_STATUS_LANE0 0x0270
#define RO_DPHY_RX_STATE_CHK_ERR_LANE0_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE0_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE0_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE0_MASK (0x7 << 4)
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE0_SHIFT 16
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE0_MASK (0x7 << 16)
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE0_SHIFT 20
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE0_MASK (0x7 << 20)
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE0_SHIFT 24
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE0_MASK (0x7 << 24)
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE0_SHIFT 28
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE0_MASK (0x7 << 28)

#define DPHY_RX_STATE_CHK_STATUS_LANE1 0x0274
#define RO_DPHY_RX_STATE_CHK_ERR_LANE1_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE1_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE1_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE1_MASK (0x7 << 4)
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE1_SHIFT 16
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE1_MASK (0x7 << 16)
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE1_SHIFT 20
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE1_MASK (0x7 << 20)
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE1_SHIFT 24
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE1_MASK (0x7 << 24)
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE1_SHIFT 28
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE1_MASK (0x7 << 28)

#define DPHY_RX_STATE_CHK_STATUS_LANE2 0x0278
#define RO_DPHY_RX_STATE_CHK_ERR_LANE2_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE2_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE2_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE2_MASK (0x7 << 4)
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE2_SHIFT 16
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE2_MASK (0x7 << 16)
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE2_SHIFT 20
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE2_MASK (0x7 << 20)
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE2_SHIFT 24
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE2_MASK (0x7 << 24)
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE2_SHIFT 28
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE2_MASK (0x7 << 28)

#define DPHY_RX_STATE_CHK_STATUS_LANE3 0x027c
#define RO_DPHY_RX_STATE_CHK_ERR_LANE3_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE3_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE3_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE3_MASK (0x7 << 4)
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE3_SHIFT 16
#define DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE3_MASK (0x7 << 16)
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE3_SHIFT 20
#define DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE3_MASK (0x7 << 20)
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE3_SHIFT 24
#define DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE3_MASK (0x7 << 24)
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE3_SHIFT 28
#define DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE3_MASK (0x7 << 28)

#define CDPHY_DEBUG_PORT_SELECT 0x0280
#define RG_CSI_CDPHY_DBG_PORT_SEL_SHIFT 0
#define RG_CSI_CDPHY_DBG_PORT_SEL_MASK (0xffffffff << 0)

#define CDPHY_DEBUG_MODE_SELECT 0x0284
#define RG_CSI_CDPHY_DBG_MOD_SEL_SHIFT 0
#define RG_CSI_CDPHY_DBG_MOD_SEL_MASK (0xffff << 0)

#define CDPHY_DEBUG_OUT_READ 0x0288
#define RO_CSI_CDPHY_DBG_OUT_READ_SHIFT 0
#define RO_CSI_CDPHY_DBG_OUT_READ_MASK (0xffffffff << 0)

#define DPHY_RX_INIT 0x028c
#define RG_CSI2_TINIT_CNT_SHIFT 0
#define RG_CSI2_TINIT_CNT_MASK (0xfffff << 0)
#define RG_CSI2_TINIT_CNT_EN_SHIFT 31
#define RG_CSI2_TINIT_CNT_EN_MASK (0x1 << 31)


#endif
