
obj-$(CONFIG_AMLOGIC_PAGE_TRACE)  += page_trace.o
obj-$(CONFIG_AMLOGIC_CMA)         += aml_cma.o
obj-$(CONFIG_AMLOGIC_SLUB_DEBUG)  += aml_slub_debug.o
obj-$(CONFIG_AMLOGIC_RAMDUMP)     += ram_dump.o
obj-$(CONFIG_AMLOGIC_VMAP)        += vmap_stack.o
