# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_IMX_DSP)		+= imx-dsp.o
obj-$(CONFIG_IMX_SCU)		+= imx-scu.o misc.o imx-scu-irq.o rm.o imx-scu-soc.o seco.o
obj-$(CONFIG_IMX_SCU_PD)	+= scu-pd.o
obj-${CONFIG_IMX_SECO_MU}	+= seco_mu.o
obj-${CONFIG_IMX_SENTNL_MU}	+= sentnl_mu.o sentnl_base_msg.o
