obj-$(CONFIG_HAVE_IMX_GPC) += gpc.o
obj-$(CONFIG_IMX7_PM_DOMAINS) += gpcv2.o
obj-$(CONFIG_HAVE_IMX_MU) += mu/
obj-$(CONFIG_HAVE_IMX_SC) += sc/
obj-$(CONFIG_HAVE_IMX_SC_PD) += pm-domains.o
obj-$(CONFIG_HAVE_IMX8_SOC) += soc-imx8.o
obj-$(CONFIG_HAVE_IMX_GPC_PSCI) += gpc-psci.o
