##########################################
########## Amlogic Drivers ###############
##########################################

##########################################
## The order of directories matter.
## Do not change.
##########################################


obj-$(CONFIG_AMLOGIC_UART)	+= uart/

obj-$(CONFIG_AMLOGIC_IOMAP)	+= iomap/
