hdpvr-objs	:= hdpvr-control.o hdpvr-core.o hdpvr-video.o hdpvr-i2c.o

obj-$(CONFIG_VIDEO_HDPVR) += hdpvr.o

EXTRA_CFLAGS += -Idrivers/media/platform

EXTRA_CFLAGS += $(extra-cflags-y) $(extra-cflags-m)
