#
# AMLOGIC VE & CM.
#

obj-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_VECM) += am_vecm.o
am_vecm-objs := amve.o
am_vecm-objs += amcm.o
am_vecm-objs += amcsc.o
am_vecm-objs += amvecm.o
am_vecm-objs += keystone_correction.o
am_vecm-objs += bitdepth.o
am_vecm-objs += set_hdr2_v0.o
am_vecm-objs += dnlp_cal.o
am_vecm-objs += cm2_adj.o
am_vecm-objs += vlock.o
am_vecm-objs += hdr/am_hdr10_plus.o
am_vecm-objs += local_contrast.o
am_vecm-objs += amvecm_drm.o
