
obj-$(CONFIG_BATTERY_SAMSUNG)		+= sec_battery.o
obj-$(CONFIG_SEC_BOARD_MXC)		+= sec_board-mxc.o
obj-$(CONFIG_FUELGAUGE_MAX77823)	+= max77823_fuelgauge.o

obj-$(CONFIG_CHARGER_MAX77823)		+= max77823_charger.o
