obj-$(CONFIG_MXC_IPU_V1)			+= ipu/
obj-$(CONFIG_MXC_IPU_V3)			+= ipu3/
obj-$(CONFIG_MXC_SSI)               	+= ssi/
obj-$(CONFIG_MXC_DAM)               	+= dam/

obj-$(CONFIG_MXC_PMIC_MC9SDZ60)		+= mcu_pmic/
obj-$(CONFIG_MXC_PMIC)			+= pmic/

obj-$(CONFIG_MXC_HMP4E)         	+= hmp4e/
obj-y                                   += security/
obj-$(CONFIG_MXC_VPU)                   += vpu/
obj-$(CONFIG_MXC_HWEVENT)               += hw_event/
obj-$(CONFIG_MXC_ASRC)                 += asrc/
obj-$(CONFIG_MXC_BLUETOOTH)		+= bt/
obj-$(CONFIG_GPS_IOCTRL)		+= gps_ioctrl/
obj-$(CONFIG_MXC_MLB)                   += mlb/
obj-$(CONFIG_IMX_ADC)                   += adc/
obj-$(CONFIG_MXC_AMD_GPU)		+= amd-gpu/
