#
# AMLOGIC NAND driver for mtd subsystem
#

obj-$(CONFIG_AMLOGIC_M8B_NAND) +=   aml_nand.o \
				m3_nand.o \
				env_old.o \
				nand_key.o \
				nand_flash.o \
				mtd_driver.o \
				new_nand.o \
				secure_storage.o
