#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_FTS) += focaltech_upgrade_idc.o
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_FTS) += focaltech_upgrade_ft7250.o
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_FTS) += focaltech_upgrade_test.o
