/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 * Copyright (c) 2021 BayLibre, SAS
 */

#ifndef _MTK_HDMI_REGS_H
#define _MTK_HDMI_REGS_H

#define AIF_HEADER GENMASK(19, 0)
#define AIF_PKT00 GENMASK(31, 0)
#define AIF_PKT01 (23, 0)
#define AIF_PKT02 (31, 0)
#define AIF_PKT03 (23, 0)

#define AIP_CTRL 0x400
#define AIP_CTS_SVAL 0x408
#define AIP_DOWNSAMPLE_CTRL 0x41C
#define AIP_I2S_CHST0 0x414
#define AIP_I2S_CHST1 0x418
#define AIP_I2S_CTRL 0x410
#define AIP_N_VAL 0x404
#define AIP_SPDIF_CTRL 0x40C
#define AIP_TPI_CTRL 0x428
#define AIP_TXCTRL 0x424

#define AUD_DIS (0x0)
#define AUD_DIS_WR (0x0)
#define AUD_EN BIT(2)
#define AUD_EN_WR BIT(18)
#define AUD_ERR_THRESH GENMASK(29, 24)
#define AUD_ERR_THRESH_SHIFT 24
#define AUD_IN_EN BIT(8)
#define AUD_IN_EN_SHIFT 8
#define AUD_MUTE_DIS (0x0)
#define AUD_MUTE_FIFO_EN BIT(5)
#define AUD_PACKET_DROP BIT(6)
#define AUD_RPT_DIS (0x0)
#define AUD_RPT_EN BIT(2)
#define AUD_SEL_OWRT BIT(9)

#define AVI_DIS (0)
#define AVI_DIS_WR (0)
#define AVI_EN (0x1)
#define AVI_EN_WR BIT(16)
#define AVI_HEADER GENMASK(23, 0)
#define AVI_PKT00 GENMASK(31, 0)
#define AVI_PKT01 GENMASK(23, 0)
#define AVI_PKT02 GENMASK(31, 0)
#define AVI_PKT03 GENMASK(23, 0)
#define AVI_PKT04 GENMASK(31, 0)
#define AVI_PKT05 GENMASK(23, 0)
#define AVI_RPT_DIS (0x0)
#define AVI_RPT_EN (0x1)

#define C422_C420_CONFIG_BYPASS BIT(5)
#define C422_C420_CONFIG_ENABLE BIT(4)
#define C422_C420_CONFIG_OUT_CB_OR_CR BIT(6)
#define C444_C422_CONFIG_ENABLE (0x1)

#define CBIT_ORDER_SAME BIT(13)

#define CEA_AUD_EN BIT(9)
#define CEA_AVI_EN BIT(11)
#define CEA_CP_EN BIT(6)
#define CEA_SPD_EN BIT(10)

#define CLEAR_FIFO 0x9

#define CLOCK_SCL 0xA

#define CP_CLR_MUTE_EN BIT(1)
#define CP_EN BIT(5)
#define CP_EN_WR BIT(21)
#define CP_RPT_EN BIT(5)
#define CP_SET_MUTE_DIS (0)
#define CP_SET_MUTE_EN (1)

#define CTS_CAL_N4 BIT(23)
#define CTS_REQ_EN BIT(1)
#define CTS_SW_SEL (1)

#define C_SD0 (0x0)
#define C_SD1 BIT(4)
#define C_SD2 BIT(9)
#define C_SD3 GENMASK(13, 12)
#define C_SD4 BIT(18)
#define C_SD5 (0x5 << 20)
#define C_SD6 GENMASK(26, 25)
#define C_SD7 GENMASK(30, 28)

#define DATA_DIR_LSB BIT(9)
#define DATA_DIR_MSB (0)

#define DDC_CMD GENMASK(31, 28)
#define DDC_CMD_SHIFT (28)
#define DDC_CTRL 0xC10
#define DDC_DATA_OUT GENMASK(23, 16)
#define DDC_DATA_OUT_SHIFT (16)
#define DDC_DELAY_CNT GENMASK(31, 16)
#define DDC_DELAY_CNT_SHIFT (16)
#define DDC_DIN_CNT (25, 16)
#define DDC_DIN_CNT_SHIFT (16)
#define DDC_I2C_BUS_LOW BIT(11)
#define DDC_I2C_IN_PROG BIT(13)
#define DDC_I2C_IN_PROG_INT_CLR BIT(29)
#define DDC_I2C_IN_PROG_INT_MASK (0)
#define DDC_I2C_IN_PROG_INT_UNMASK BIT(29)
#define DDC_I2C_NO_ACK BIT(10)
#define DDC_OFFSET GENMASK(15, 8)
#define DDC_OFFSET_SHIFT (8)
#define DDC_SEGMENT GENMASK(15, 8)
#define DDC_SEGMENT_SHIFT (8)

#define DEEPCOLOR_MODE_10BIT BIT(8)
#define DEEPCOLOR_MODE_12BIT GENMASK(9, 8)
#define DEEPCOLOR_MODE_16BIT GENMASK(10, 8)
#define DEEPCOLOR_MODE_8BIT (0)
#define DEEPCOLOR_MODE_MASKBIT GENMASK(10, 8)
#define DEEPCOLOR_PAT_EN BIT(12)
#define DEEP_COLOR_ADD BIT(4)

#define DOWNSAMPLE 0x2

#define DSD_EN BIT(15)
#define DSD_MUTE_DATA BIT(7)

#define ENH_READ_NO_ACK 0x4

#define FIFO0_MAP GENMASK(1, 0)
#define FIFO1_MAP GENMASK(3, 2)
#define FIFO2_MAP GENMASK(5, 4)
#define FIFO3_MAP GENMASK(7, 6)

#define FS_OVERRIDE_WRITE BIT(1)
#define FS_UNOVERRIDE (0)

#define HBRA_ON BIT(14)

#define HBR_FROM_SPDIF BIT(20)

#define HDMI2_OFF (0)
#define HDMI2_ON BIT(2)

#define HDMITX_SW_HPD BIT(29)
#define HDMITX_SW_HPD_SHIFT (29)
#define HDMITX_SW_RSTB BIT(31)
#define HDMITX_SW_RSTB_SHIFT (31)

#define HDMI_MODE_DVI (0)
#define HDMI_MODE_HDMI BIT(3)

#define HDMI_YUV420_MODE BIT(10)
#define HDMI_YUV420_MODE_SHIFT (10)

#define HPD_DDC_CTRL 0xC08
#define HPD_DDC_STATUS 0xC60
#define DDC_DATA_OUT_SHIFT (16)
#define DDC_FIFO_FULL BIT(15)
#define DDC_FIFO_EMPTY BIT(14)
#define DDC_I2C_IN_PROG BIT(13)
#define DDC_DATA_OUT_CNT (0x1F << 8)
#define RX_HDCP2_CAP_EN BIT(7)
#define HDCP2_AUTH_RXCAP_FAIL BIT(6)
#define PORD_PIN_STA BIT(5)
#define HPD_PIN_STA BIT(4)
#define PORD_STATE (0x3 << 2)
#define PORD_STATE_SHIFT (2)
#define PORD_STATE_CONNECTED (2)
#define PORD_STATE_DISCONNECTED (0)
#define HPD_STATE (0x3 << 0)
#define HPD_STATE_SHIFT (0)
#define HPD_STATE_CONNECTED (2)
#define HPD_STATE_DISCONNECTED (0)

#define HTPLG_F_INT_STA BIT(1)
#define HTPLG_R_INT_STA BIT(0)

#define I2S2DSD_EN BIT(30)
#define I2S_1ST_BIT_NOSHIFT BIT(8)
#define I2S_EN GENMASK(19, 16)
#define I2S_EN_SHIFT 16

#define JUSTIFY_RIGHT BIT(10)

#define LAYOUT BIT(18)
#define LAYOUT0 0
#define LAYOUT1 BIT(4)

#define LFE_CC_SWAP BIT(1)

#define MAP_SD0 0x0
#define MAP_SD1 0x1
#define MAP_SD2 0x2
#define MAP_SD3 0x3

#define MAX_1UI_WRITE GENMASK(15, 8)
#define MAX_1UI_WRITE_SHIFT 8
#define MAX_2UI_WRITE GENMASK(23, 16)
#define MAX_2UI_WRITE_SHIFT 16

#define MCLK_1152FS 0x6
#define MCLK_128FS 0x0
#define MCLK_192FS 0x7
#define MCLK_256FS 0x1
#define MCLK_384FS 0x2
#define MCLK_512FS 0x3
#define MCLK_768FS 0x4
#define MCLK_CTSGEN_SEL 0
#define MCLK_EN BIT(2)
#define NO_MCLK_CTSGEN_SEL BIT(3)

#define NULL_PKT_EN BIT(2)
#define NULL_PKT_VSYNC_HIGH_EN BIT(3)

#define OUTPUT_FORMAT_DEMUX_420_ENABLE BIT(10)

#define PORD_F_INT_STA BIT(3)
#define PORD_PIN_STA BIT(5)
#define PORD_R_INT_STA BIT(2)

#define REG_VMUTE_EN BIT(16)
#define RST4AUDIO BIT(0)
#define RST4AUDIO_ACR BIT(2)
#define RST4AUDIO_FIFO BIT(1)

#define SCDC_CTRL 0xC18

#define SCK_EDGE_RISE BIT(14)

#define SCR_OFF 0
#define SCR_ON BIT(4)

#define SEQ_READ_NO_ACK 0x2
#define SEQ_WRITE_REQ_ACK 0x7

#define SI2C_CTRL 0xCAC
#define SI2C_ADDR GENMASK(23, 16)
#define SI2C_ADDR_READ (0xF4)
#define SI2C_ADDR_SHIFT (16)
#define SI2C_WDATA GENMASK(15, 8)
#define SI2C_WDATA_SHIFT (8)
#define RX_CAP_RD_TRIG BIT(5)
#define KSV_RD BIT(4)
#define SI2C_STOP BIT(3)
#define SI2C_CONFIRM_READ BIT(2)
#define SI2C_RD BIT(1)
#define SI2C_WR BIT(0)

#define SPDIF_EN BIT(13)
#define SPDIF_EN_SHIFT 13
#define SPDIF_HEADER GENMASK(23, 0)
#define SPDIF_INTERNAL_MODULE BIT(24)
#define SPDIF_PKT00 GENMASK(31, 0)
#define SPDIF_PKT01 GENMASK(23, 0)
#define SPDIF_PKT02 GENMASK(31, 0)
#define SPDIF_PKT03 GENMASK(23, 0)
#define SPDIF_PKT04 GENMASK(31, 0)
#define SPDIF_PKT05 GENMASK(23, 0)
#define SPDIF_PKT06 GENMASK(31, 0)
#define SPDIF_PKT07 GENMASK(23, 0)

#define SPD_DIS 0
#define SPD_DIS_WR 0
#define SPD_EN BIT(1)
#define SPD_EN_WR BIT(17)
#define SPD_RPT_DIS 0
#define SPD_RPT_EN BIT(1)

#define TOP_AIF_HEADER 0x040
#define TOP_AIF_PKT00 0x044
#define TOP_AIF_PKT01 0x048
#define TOP_AIF_PKT02 0x04C
#define TOP_AIF_PKT03 0x050
#define TOP_AUD_MAP 0x00C
#define TOP_AVI_HEADER 0x024
#define TOP_AVI_PKT00 0x028
#define TOP_AVI_PKT01 0x02C
#define TOP_AVI_PKT02 0x030
#define TOP_AVI_PKT03 0x034
#define TOP_AVI_PKT04 0x038
#define TOP_AVI_PKT05 0x03C
#define TOP_CFG00 0x000
#define TOP_CFG01 0x004
#define TOP_INFO_EN 0x01C
#define TOP_INFO_EN_EXPAND 0x368
#define TOP_INFO_RPT 0x020
#define TOP_INT_CLR00 0x1B8
#define DDC_FIFO_HALF_FULL_INT_CLR BIT(31)
#define DDC_FIFO_FULL_INT_CLR BIT(30)
#define DDC_I2C_IN_PROG_INT_CLR BIT(29)
#define HDCP_RI_128_INT_CLR BIT(28)
#define HDCP_SHA_START_INT_CLR BIT(27)
#define HDCP2X_RX_RPT_READY_DDCM_INT_CLR BIT(26)
#define HDCP2X_RX_REAUTH_REQ_DDCM_INT_CLR BIT(25)
#define HDCP2X_RPT_SMNG_XFER_DONE_INT_CLR BIT(24)
#define HDCP2X_RPT_RCVID_CHANGED_INT_CLR BIT(23)
#define HDCP2X_CERT_SEND_RCVD_INT_CLR BIT(22)
#define HDCP2X_SKE_SENT_RCVD_INT_CLR BIT(21)
#define HDCP2X_AKE_SENT_RCVD_INT_CLR BIT(20)
#define HDCP2X_HASH_FAIL_INT_CLR BIT(19)
#define HDCP2X_CCHK_DONE_INT_CLR BIT(18)
#define HDCP2X_AUTH_FAIL_INT_CLR BIT(17)
#define HDCP2X_AUTH_DONE_INT_CLR BIT(16)
#define HDCP2X_MSG_7_INT_CLR BIT(15)
#define HDCP2X_MSG_6_INT_CLR BIT(14)
#define HDCP2X_MSG_5_INT_CLR BIT(13)
#define HDCP2X_MSG_4_INT_CLR BIT(12)
#define HDCP2X_MSG_3_INT_CLR BIT(11)
#define HDCP2X_MSG_2_INT_CLR BIT(10)
#define HDCP2X_MSG_1_INT_CLR BIT(9)
#define HDCP2X_MSG_0_INT_CLR BIT(8)
#define INFO_DONE_INT_CLR BIT(7)
#define PB_FULL_INT_CLR BIT(6)
#define AUDIO_INT_CLR BIT(5)
#define VSYNC_INT_CLR BIT(4)
#define PORD_F_INT_CLR BIT(3)
#define PORD_R_INT_CLR BIT(2)
#define HTPLG_F_INT_CLR BIT(1)
#define HTPLG_R_INT_CLR BIT(0)
#define DDC_FIFO_HALF_FULL_INT_UNCLR (0 << 31)
#define DDC_FIFO_FULL_INT_UNCLR (0 << 30)
#define DDC_I2C_IN_PROG_INT_UNCLR (0 << 29)
#define HDCP_RI_128_INT_UNCLR (0 << 28)
#define HDCP_SHA_START_INT_UNCLR (0 << 27)
#define HDCP2X_RX_RPT_READY_DDCM_INT_UNCLR (0 << 26)
#define HDCP2X_RX_REAUTH_REQ_DDCM_INT_UNCLR (0 << 25)
#define HDCP2X_RPT_SMNG_XFER_DONE_INT_UNCLR (0 << 24)
#define HDCP2X_RPT_RCVID_CHANGED_INT_UNCLR (0 << 23)
#define HDCP2X_CERT_SEND_RCVD_INT_UNCLR (0 << 22)
#define HDCP2X_SKE_SENT_RCVD_INT_UNCLR (0 << 21)
#define HDCP2X_AKE_SENT_RCVD_INT_UNCLR (0 << 20)
#define HDCP2X_HASH_FAIL_INT_UNCLR (0 << 19)
#define HDCP2X_CCHK_DONE_INT_UNCLR (0 << 18)
#define HDCP2X_AUTH_FAIL_INT_UNCLR (0 << 17)
#define HDCP2X_AUTH_DONE_INT_UNCLR (0 << 16)
#define HDCP2X_MSG_7_INT_UNCLR (0 << 15)
#define HDCP2X_MSG_6_INT_UNCLR (0 << 14)
#define HDCP2X_MSG_5_INT_UNCLR (0 << 13)
#define HDCP2X_MSG_4_INT_UNCLR (0 << 12)
#define HDCP2X_MSG_3_INT_UNCLR (0 << 11)
#define HDCP2X_MSG_2_INT_UNCLR (0 << 10)
#define HDCP2X_MSG_1_INT_UNCLR (0 << 9)
#define HDCP2X_MSG_0_INT_UNCLR (0 << 8)
#define INFO_DONE_INT_UNCLR (0 << 7)
#define PB_FULL_INT_UNCLR (0 << 6)
#define AUDIO_INT_UNCLR (0 << 5)
#define VSYNC_INT_UNCLR (0 << 4)
#define PORD_F_INT_UNCLR (0 << 3)
#define PORD_R_INT_UNCLR (0 << 2)
#define HTPLG_F_INT_UNCLR (0 << 1)
#define HTPLG_R_INT_UNCLR (0 << 0)

#define TOP_INT_CLR01 0x1BC
#define TOP_INT_MASK00 0x1B0
#define HDCP2X_RX_REAUTH_REQ_DDCM_INT_MASK (0)
#define HDCP2X_RX_REAUTH_REQ_DDCM_INT_UNMASK BIT(25)

#define TOP_INT_MASK01 0x1B4
#define TOP_INT_STA00 0x1A8
#define DDC_FIFO_HALF_FULL_INT_STA BIT(31)
#define DDC_FIFO_FULL_INT_STA BIT(30)
#define DDC_I2C_IN_PROG_INT_STA BIT(29)
#define HDCP_RI_128_INT_STA BIT(28)
#define HDCP_SHA_START_INT_STA BIT(27)
#define HDCP2X_RX_RPT_READY_DDCM_INT_STA BIT(26)
#define HDCP2X_RX_REAUTH_REQ_DDCM_INT_STA BIT(25)
#define HDCP2X_RPT_SMNG_XFER_DONE_INT_STA BIT(24)
#define HDCP2X_RPT_RCVID_CHANGED_INT_STA BIT(23)
#define HDCP2X_CERT_SEND_RCVD_INT_STA BIT(22)
#define HDCP2X_SKE_SENT_RCVD_INT_STA BIT(21)
#define HDCP2X_AKE_SENT_RCVD_INT_STA BIT(20)
#define HDCP2X_HASH_FAIL_INT_STA BIT(19)
#define HDCP2X_CCHK_DONE_INT_STA BIT(18)
#define HDCP2X_AUTH_FAIL_INT_STA BIT(17)
#define HDCP2X_AUTH_DONE_INT_STA BIT(16)
#define HDCP2X_MSG_7_INT_STA BIT(15)
#define HDCP2X_MSG_6_INT_STA BIT(14)
#define HDCP2X_MSG_5_INT_STA BIT(13)
#define HDCP2X_MSG_4_INT_STA BIT(12)
#define HDCP2X_MSG_3_INT_STA BIT(11)
#define HDCP2X_MSG_2_INT_STA BIT(10)
#define HDCP2X_MSG_1_INT_STA BIT(9)
#define HDCP2X_MSG_0_INT_STA BIT(8)
#define INFO_DONE_INT_STA BIT(7)
#define PB_FULL_INT_STA BIT(6)
#define AUDIO_INT_STA BIT(5)
#define VSYNC_INT_STA BIT(4)
#define PORD_F_INT_STA BIT(3)
#define PORD_R_INT_STA BIT(2)
#define HTPLG_F_INT_STA BIT(1)
#define HTPLG_R_INT_STA BIT(0)

#define TOP_MISC_CTLR 0x1A4
#define DISABLE_IDLE_DDC_RESET BIT(7)

#define TOP_SPDIF_HEADER 0x054
#define TOP_SPDIF_PKT00 0x058
#define TOP_SPDIF_PKT01 0x05C
#define TOP_SPDIF_PKT02 0x060
#define TOP_SPDIF_PKT03 0x064
#define TOP_SPDIF_PKT04 0x068
#define TOP_SPDIF_PKT05 0x06C
#define TOP_SPDIF_PKT06 0x070
#define TOP_SPDIF_PKT07 0x074
#define TOP_VMUTE_CFG1 0x1C8

#define TPI_AUDIO_LOOKUP_DIS 0
#define TPI_AUDIO_LOOKUP_EN BIT(2)

#define VBIT_COM BIT(12)
#define VBIT_PCM 0

#define VID_DOWNSAMPLE_CONFIG 0x8F0
#define VID_OUT_FORMAT 0x8FC

#define WR_1UI_LOCK BIT(0)
#define WR_1UI_UNLOCK 0
#define WR_2UI_LOCK BIT(2)
#define WR_2UI_UNLOCK 0
#define WS_HIGH BIT(11)

#define ABIST_ENABLE (1 << 31)
#define ABIST_VIDEO_FORMAT_MASKBIT (0x3F << 16)
#define ABIST_VIDEO_FORMAT_720x480P (0x2 << 16)
#define ABIST_VIDEO_FORMAT_720P50 (0xC << 16)
#define ABIST_VIDEO_FORMAT_1080P60 (0xA << 16)
#define ABIST_VIDEO_FORMAT_3840x2160P30 (0x19 << 16)

/* HDCP related registers */
#define TOP_CLK_RST_CFG 0x1A0
#define SLOW_CLK_DIV_CNT (0xFF << 16)
#define RISC_CLK_DDC_RST (0x1 << 15)
#define HDCP_1P4_TCLK_EN (0x1 << 9)
#define HDCP_1P4_TCLK_DIS (0x0 << 9)
#define HDCP_TCLK_EN (0x1 << 8)
#define HDCP_TCLK_DIS (0x0 << 8)
#define SOFT_VIDEO_RST (0x1 << 5)
#define SOFT_VIDEO_NOR (0x0 << 5)
#define SOFT_HDCP_1P4_RST (0x1 << 2)
#define SOFT_HDCP_1P4_NOR (0x0 << 2)
#define SOFT_HDCP_CORE_RST (0x1 << 1)
#define SOFT_HDCP_CORE_NOR (0x0 << 1)
#define SOFT_HDCP_RST (0x1 << 0)
#define SOFT_HDCP_NOR (0x0 << 0)

#define TOP_INT_STA01 0x1AC
#define HDCP_TOP_CTRL 0xC00

#define TXDS_BSTATUS 0xC1C
#define HDCP2X_CTRL_0 0xC20
#define HDCP2X_CPVER (0xF << 20)
#define HDCP2X_CUPD_START BIT(16)
#define HDCP2X_REAUTH_MSK (0xF << 12)
#define HDCP2X_REAUTH_MSK_SHIFT (12)
#define HDCP2X_HPD_SW BIT(11)
#define HDCP2X_HPD_OVR BIT(10)
#define HDCP2X_CTL3MSK BIT(9)
#define HDCP2X_REAUTH_SW BIT(8)
#define HDCP2X_ENCRYPT_EN BIT(7)
#define HDCP2X_ENCRYPT_EN_SHIFT (7)
#define HDCP2X_POLINT_SEL BIT(6)
#define HDCP2X_POLINT_OVR BIT(5)
#define HDCP2X_PRECOMPUTE BIT(4)
#define HDCP2X_HDMIMODE BIT(3)
#define HDCP2X_REPEATER BIT(2)
#define HDCP2X_HDCPTX BIT(1)
#define HDCP2X_EN BIT(0)

#define HDCP2X_CTRL_1 0xC24
#define HDCP2X_CUPD_SIZE (0xFFFF << 0)

#define HDCP2X_CTRL_2 0xC28
#define HDCP2X_RINGOSC_BIST_START BIT(28)
#define HDCP2X_MSG_SZ_CLR_OPTION BIT(26)
#define HDCP2X_RPT_READY_CLR_OPTION BIT(25)
#define HDCP2X_REAUTH_REQ_CLR_OPTION BIT(24)
#define HDCP2X_RPT_SMNG_IN (0xFF << 16)
#define HDCP2X_RPT_SMNG_K (0xFF << 8)
#define HDCP2X_RPT_SMNG_XFER_START BIT(4)
#define HDCP2X_RPT_SMNG_WR_START BIT(3)
#define HDCP2X_RPT_SMNG_WR BIT(2)
#define HDCP2X_RPT_RCVID_RD_START BIT(1)
#define HDCP2X_RPT_RCVID_RD BIT(0)
#define HDCP2X_RPT_SMNG_K_SHIFT (8)
#define HDCP2X_RPT_SMNG_IN_SHIFT (16)

#define HDCP2X_CTRL_STM 0xC2C
#define HDCP2X_STM_CTR (0xFFFFFFFF << 0)

#define HDCP2X_TEST_TP0 0xC30
#define HDCP2X_TP3 (0xFF << 24)
#define HDCP2X_TP2 (0xFF << 16)
#define HDCP2X_TP1 (0xFF << 8)
#define HDCP2X_TP0 (0xFF << 0)
#define HDCP2X_TP3_SHIFT (24)
#define HDCP2X_TP2_SHIFT (16)
#define HDCP2X_TP1_SHIFT (8)
#define HDCP2X_TP0_SHIFT (0)

#define HDCP2X_TEST_TP1 0xC34
#define HDCP2X_TP7 (0xFF << 24)
#define HDCP2X_TP6 (0xFF << 16)
#define HDCP2X_TP5 (0xFF << 8)
#define HDCP2X_TP4 (0xFF << 0)

#define HDCP2X_TEST_TP2 0xC38
#define HDCP2X_TP11 (0xFF << 24)
#define HDCP2X_TP10 (0xFF << 16)
#define HDCP2X_TP9 (0xFF << 8)
#define HDCP2X_TP8 (0xFF << 0)

#define HDCP2X_TEST_TP3 0xC3C
#define HDCP2X_TP15 (0xFF << 24)
#define HDCP2X_TP14 (0xFF << 16)
#define HDCP2X_TP13 (0xFF << 8)
#define HDCP2X_TP12 (0xFF << 0)

#define HDCP2X_GP_IN 0xC40
#define HDCP2X_GP_IN3 (0xFF << 24)
#define HDCP2X_GP_IN2 (0xFF << 16)
#define HDCP2X_GP_IN1 (0xFF << 8)
#define HDCP2X_GP_IN0 (0xFF << 0)
#define HDCP2X_GP_IN3_SHIFT (24)
#define HDCP2X_GP_IN2_SHIFT (16)
#define HDCP2X_GP_IN1_SHIFT (8)
#define HDCP2X_GP_IN0_SHIFT (0)

#define HDCP2X_DEBUG_CTRL 0xC44
#define HDCP2X_DB_CTRL3 (0xFF << 24)
#define HDCP2X_DB_CTRL2 (0xFF << 16)
#define HDCP2X_DB_CTRL1 (0xFF << 8)
#define HDCP2X_DB_CTRL0 (0xFF << 0)

#define HDCP2X_SPI_SI_ADDR 0xC48
#define HDCP2X_SPI_SI_S_ADDR (0xFFFF << 16)
#define HDCP2X_SPI_SI_E_ADDR (0xFFFF << 0)

#define HDCP2X_SPI_ADDR_CTRL 0xC4C
#define HDCP2X_DB_CTRL4 (0xFFFF << 16)
#define HDCP2X_SPI_S_ADDR (0xFFFF << 0)

#define HDCP2X_RPT_SEQ_NUM 0xC50
#define MHL3_P0_STM_ID (0x7 << 24)
#define HDCP2X_RPT_SEQ_NUM_M (0xFFFFFF << 0)

#define HDCP2X_POL_CTRL 0xC54
#define HDCP2X_DIS_POLL_EN BIT(16)
#define HDCP2X_POL_VAL1 (0xFF << 8)
#define HDCP2X_POL_VAL0 (0xFF << 0)

#define WR_PULSE 0xC58
#define HDCP2X_SPI_ADDR_RESET BIT(3)
#define DDC_BUS_LOW BIT(2)
#define DDC_NO_ACK BIT(1)
#define DDCM_ABORT BIT(0)

#define SCDC_STATUS 0xC64
#define SCDC_STATE (0xF << 28)
#define SCDC_RREQ_STATE (0xF << 24)
#define SCDC_UP_FLAG1_STATUS (0xFF << 16)
#define SCDC_UP_FLAG0_STATUS (0xFF << 8)
#define SCDC_UP_FLAG_DONE BIT(6)
#define SCDC_SLAVE_RD_REQ_P BIT(5)
#define SCDC_DDC_CONFLICT BIT(4)
#define SCDC_DDC_DONE BIT(3)
#define SCDC_IN_PROG BIT(2)
#define SCDC_RREQ_IN_PROG BIT(1)
#define SCDC_ACTIVE BIT(0)

#define HDCP2X_DDCM_STATUS 0xC68

#define KSV_RI_STATUS 0xC78
#define HDCP2X_DEBUG_STATUS_0 0xC7C
#define HDCP2X_DEBUG_STAT3 (0xFF << 24)
#define HDCP2X_DEBUG_STAT2 (0xFF << 16)
#define HDCP2X_DEBUG_STAT1 (0xFF << 8)
#define HDCP2X_DEBUG_STAT0 (0xFF << 0)

#define HDCP2X_DEBUG_STATUS_1 0xC80
#define HDCP2X_DEBUG_STAT7 (0xFF << 24)
#define HDCP2X_DEBUG_STAT6 (0xFF << 16)
#define HDCP2X_DEBUG_STAT5 (0xFF << 8)
#define HDCP2X_DEBUG_STAT4 (0xFF << 0)

#define HDCP2X_DEBUG_STATUS_2 0xC84
#define HDCP2X_DEBUG_STAT11 (0xFF << 24)
#define HDCP2X_DEBUG_STAT10 (0xFF << 16)
#define HDCP2X_DEBUG_STAT9 (0xFF << 8)
#define HDCP2X_DEBUG_STAT8 (0xFF << 0)

#define HDCP2X_DEBUG_STATUS_3 0xC88
#define HDCP2X_DEBUG_STAT15 (0xFF << 24)
#define HDCP2X_DEBUG_STAT14 (0xFF << 16)
#define HDCP2X_DEBUG_STAT13 (0xFF << 8)
#define HDCP2X_DEBUG_STAT12 (0xFF << 0)

#define HDCP2X_STATUS_0 0xC8C
#define HDCP2X_AUTH_STAT (0xFF << 24)
#define HDCP2X_STATE (0xFF << 16)
#define HDCP2X_ENCRYPTING_ON BIT(10)
#define HDCP2X_RPT_REPEATER BIT(8)
#define HDCP2X_PRG_SEL BIT(7)
#define HDCP2X_CUPD_DONE BIT(6)
#define HDCP2X_RPT_MX_DEVS_EXC BIT(5)
#define HDCP2X_RPT_MAX_CASC_EXC BIT(4)
#define HDCP2X_RPT_HDCP20RPT_DSTRM BIT(3)
#define HDCP2X_RPT_HDCP1DEV_DSTRM BIT(2)
#define HDCP2X_RPT_RCVID_CHANGED BIT(1)
#define HDCP2X_RPT_SMNG_XFER_DONE BIT(0)

#define HDCP2X_STATUS_1 0xC90
#define HDCP2X_RINGOSS_BIST_FAIL BIT(25)
#define HDCP2X_RINGOSC_BIST_DONE BIT(24)
#define HDCP2X_RPT_RCVID_OUT (0xFF << 16)
#define HDCP2X_RPT_RCVID_OUT_SHIFT (16)
#define HDCP2X_RPT_DEVCNT (0xFF << 8)
#define HDCP2X_RPT_DEVCNT_SHIFT (8)
#define HDCP2X_RPT_DEPTH (0xFF << 0)

#define HDCP2X_RCVR_ID 0xC94
#define HDCP2X_RCVR_ID_L (0xFFFFFFFF << 0)

#define HDCP2X_RPT_SEQ 0xC98
#define HDCP2X_RCVR_ID_H (0xFF << 24)
#define HDCP2X_RPT_SEQ_NUM_V (0xFFFFFF << 0)

#define HDCP2X_GP_OUT 0xC9C
#define HDCP2X_GP_OUT3 (0xFF << 24)
#define HDCP2X_GP_OUT2 (0xFF << 16)
#define HDCP2X_GP_OUT1 (0xFF << 8)
#define HDCP2X_GP_OUT0 (0xFF << 0)

#define PROM_CTRL 0xCA0
#define PROM_ADDR (0xFFFF << 16)
#define PROM_ADDR_SHIFT (16)
#define PROM_WDATA (0xFF << 8)
#define PROM_WDATA_SHIFT (8)
#define PROM_CS BIT(1)
#define PROM_WR BIT(0)

#define PRAM_CTRL 0xCA4
#define PRAM_ADDR (0xFFFF << 16)
#define PRAM_ADDR_SHIFT (16)
#define PRAM_WDATA (0xFF << 8)
#define PRAM_WDATA_SHIFT (8)
#define PRAM_CTRL_SEL BIT(2)
#define PRAM_CS BIT(1)
#define PRAM_WR BIT(0)

#define PROM_DATA 0xCA8
#define PROM_RDATA (0xFF << 8)
#define PRAM_RDATA (0xFF << 0)

#define HDCP1X_BKSV_0 0xCB0
#define HDCP1X_BKSV_1 0xCB4
#define HDCP1X_AN_0 0xCC0
#define HDCP1X_AN_1 0xCC4
#define HDCP1X_AES_CTRL 0xCCC
#define HDCP1X_CTRL 0xCD0
#define HDCP1X_ENC_EN BIT(6)
#define HDCP1X_ENC_EN_SHIFT (6)
#define RX_RPTR BIT(5)
#define RX_RPTR_SHIFT (5)
#define AN_STOP BIT(4)
#define AN_STOP_SHIFT (4)
#define KEY_LOAD_DONE BIT(2)
#define KEY_LOAD_DONE_SHIFT (2)
#define WR_AN_DONE BIT(1)
#define WR_AN_DONE_SHIFT (1)

#define HDCP1X_SHA_CTRL 0xCD4
#define HDCP1X_V_H0 0xCE0
#define HDCP1X_V_H1 0xCE4
#define HDCP1X_V_H2 0xCE8
#define HDCP1X_V_H3 0xCEC
#define HDCP1X_V_H4 0xCF0
#define HDCP1x_STATUS 0xCF4
#define HDCP_ENCRYPTING_ON BIT(26)

#endif /* _MTK_HDMI_REGS_H */
