#
# Makefile for the keyboard device drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_AMLOGIC_ADC_KEYPADS)		+= adc_keypad.o
obj-$(CONFIG_AMLOGIC_GPIO_KEY)          += gpio_keypad.o
obj-$(CONFIG_AMLOGIC_PCA9557_KEYPAD)          += pca9557_keypad.o
