obj-$(CONFIG_AMLOGIC_V4L_VIDEO2) += video_dev/
obj-$(CONFIG_AMLOGIC_POST_PROCESS_MANAGER) += ppmgr/
obj-$(CONFIG_AMLOGIC_IONVIDEO)	+= ionvideo/
obj-$(CONFIG_AMLOGIC_PIC_DEC)	+= pic_dev/
obj-$(CONFIG_AMLOGIC_VIDEOSYNC)	+= videosync/