obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_HDMI_EXT_SII9135)	+= hw_sii9135.o

hw_sii9135-objs := sii9135_iface.o \
		main.o \
		SiIAudio.o \
		SiIDiagnostic.o \
		SiIDeepColor.o \
		SiIHAL.o \
		SiIHDCP.o \
		SiIHDMIRX.o \
		SiIHLVIIC.o \
		SiIInfoPkts.o \
		SiIISR.o \
		SiIRX_API.o \
		SiIRXIO.o \
		SiISysCtrl.o \
		SiITrace.o \
		SiITTasks.o \
		SiITTAudio.o \
		SiITTHDCP.o \
		SiITTInfoPkts.o \
		SiITTVideo.o \
		SiIVidF.o \
		SiIVidIn.o \
		SiIVidRes.o \
		SiIVRTables.o \
		UDebugHLIIC.o \
		UEEPROM.o \
		UAT_EEPROM.o \
		uauddac.o \
		UCfgRX.o
