#
# Makefile for Meson m8b series unifykey.
#
obj-$(CONFIG_AMLOGIC_V7_UNIFYKEY)	+= crypto_api.o \
					storage.o \
					storage_util.o \
					key_service_routine.o \
					storage_apis.o \
					storage_util.o
