ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
dtbo-$(CONFIG_ARCH_MEDIATEK) += \
	display-dp.dtbo \
	display-dsidp.dtbo \
	display-dsi.dtbo \
	display-dsiedp.dtbo \
	display-edpdp.dtbo \
	display-edp.dtbo \
	display-edphdmi.dtbo \
	display-hdmidp.dtbo \
	display-hdmi.dtbo \
	display-headless.dtbo \

endif
