ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
dtbo-$(CONFIG_ARCH_MEDIATEK) += \
	audio-sof.dtbo \
	camera-imx219-csi0.dtbo \
	camera-imx219-csi1.dtbo \
	camera-pivariety-csi0.dtbo \
	camera-pivariety-csi1.dtbo \
	camera-tevs-csi0.dtbo \
	camera-tevs-csi1.dtbo \
	display-dp.dtbo \
	display-dsidp.dtbo \
	display-dsi.dtbo \
	display-dsiedp.dtbo \
	display-dsihdmi.dtbo \
	display-edpdp.dtbo \
	display-edp.dtbo \
	display-edphdmi.dtbo \
	display-hdmidp.dtbo \
	display-hdmi.dtbo \
	display-headless.dtbo \

endif
