dtb-$(CONFIG_ARCH_MEDIATEK) += \
	audio-sof.dtbo \
	camera-imx219-csi0.dtbo \
	camera-imx219-csi1.dtbo \
	camera-tevs-csi0.dtbo \
	camera-tevs-csi1.dtbo \
	display-dp.dtbo \
	display-dsi.dtbo \
	display-edp.dtbo \
	display-hdmidp.dtbo \
	display-hdmi.dtbo \

