# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_LIBERTAS)		+= libertas/

obj-$(CONFIG_LIBERTAS_THINFIRM)	+= libertas_tf/
obj-$(CONFIG_MWIFIEX)	+= mwifiex/
obj-$(CONFIG_MRVL8997) += mrvl8997/wlan_src/
obj-$(CONFIG_MWL8K)	+= mwl8k.o
