#
# Makefile for the mc13783 pmic drivers.
#

obj-$(CONFIG_MXC_MC13783_ADC) += pmic_adc-mod.o
obj-$(CONFIG_MXC_MC13783_AUDIO) += pmic_audio-mod.o
obj-$(CONFIG_MXC_MC13783_RTC) += pmic_rtc-mod.o
obj-$(CONFIG_MXC_MC13783_LIGHT) += pmic_light-mod.o
obj-$(CONFIG_MXC_MC13783_BATTERY) += pmic_battery-mod.o
obj-$(CONFIG_MXC_MC13783_CONNECTIVITY) += pmic_convity-mod.o
obj-$(CONFIG_MXC_MC13783_POWER) += pmic_power-mod.o
pmic_adc-mod-objs := pmic_adc.o
pmic_audio-mod-objs := pmic_audio.o
pmic_rtc-mod-objs := pmic_rtc.o
pmic_light-mod-objs := pmic_light.o
pmic_battery-mod-objs := pmic_battery.o
pmic_convity-mod-objs := pmic_convity.o
pmic_power-mod-objs := pmic_power.o
