obj-$(CONFIG_AMLOGIC_ATV_DEMOD) += aml_atvdemod.o

aml_atvdemod-objs = atvdemod_func.o atvauddemod_func.o atv_demod_v4l2.o atv_demod_driver.o atv_demod_ops.o

ccflags-y += -I.
ccflags-y += -Idrivers/media/dvb-core
