# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_MESON) += uart4.dtbo \
                            i2c0.dtbo \
                            i2s.dtbo \
                            spdifout.dtbo \
                            spdifout_i2s.dtbo

targets += $(dtbo-y)

always         := $(dtbo-y)
clean-files    := *.dtbo

