obj-y += ddr_port_desc.o
obj-$(CONFIG_AMLOGIC_DDR_WINDOW_TOOL)	+= ddr_window.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH)	+= ddr_bandwidth.o ddr_band_op_gxl.o \
					   ddr_band_op_gx.o ddr_band_op_g12.o

obj-$(CONFIG_AMLOGIC_DMC_MONITOR)	+= dmc_monitor.o \
					   dmc_g12.o dmc_gx.o

