

#EXTRA_CFLAGS += -fno-common -w
#ccflags-y += -I$(srctree)/drivers/amlogic/defendkey/include

obj-$(CONFIG_AMLOGIC_DEFENDKEY) += defendkey.o securekey.o
#obj-$(CONFIG_AMLOGIC_DEFENDKEY) += crypto/



