obj-$(CONFIG_MXC_IPU_V1) = mxc_ipu.o

mxc_ipu-objs := ipu_common_tri_buf.o ipu_sdc.o ipu_adc.o ipu_ic.o ipu_csi.o ipu_device_tri_buf.o ipu_calc_stripes_sizes.o

obj-$(CONFIG_MXC_IPU_PF)        +=   pf/
