meson-y := meson_drv.o  meson_gem.o meson_dmabuf.o
#meson-y += meson_viu.o meson_vpp.o meson_venc.o meson_vclk.o meson_canvas.o meson_plane.o meson_crtc.o meson_venc_cvbs.o

obj-$(CONFIG_DRM_MESON) += meson.o
ccflags-y += -Idrivers/staging/android/
