################################
# Amlogic codec memory manager #
################################

####################################
# The order of directories matter. #
# Do not change.                   #
####################################

obj-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM)	+=	codec_mm.o
obj-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM)	+=	codec_mm_scatter.o
obj-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM)	+=	codec_mm_keeper.o
obj-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM)	+=	configs/
