# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_MESON) += uart3.dtbo \
                            i2c3.dtbo \
                            i2s.dtbo \
                            spdifout.dtbo

targets += $(dtbo-y)

always         := $(dtbo-y)
clean-files    := *.dtbo *.scr
