#Amlogic
snd-soc-dummy_codec-objs := dummy_codec.o
snd-soc-pcm2bt-objs  := pcm2bt.o
snd-soc-aml_t9015-objs := aml_codec_t9015.o

# Amlogic
obj-$(CONFIG_AMLOGIC_SND_CODEC_DUMMY_CODEC)	+= snd-soc-dummy_codec.o
obj-$(CONFIG_AMLOGIC_SND_CODEC_PCM2BT)	+= snd-soc-pcm2bt.o
obj-$(CONFIG_AMLOGIC_SND_CODEC_AMLT9015)	+= snd-soc-aml_t9015.o