#
# Makefile for the remote control drivers
#

# Each configuration option enables a list of files.

obj-$(CONFIG_AMLOGIC_MESON_REMOTE)		+= remote.o

remote-objs := remote_core.o remote_meson.o sysfs.o remote_cdev.o remote_raw.o remote_decoder_xmp.o remote_regmap.o
