#
# Makefile for the mc13783 pmic drivers.
#

obj-$(CONFIG_MXC_MC13892_ADC) += pmic_adc.o
#obj-$(CONFIG_MXC_MC13892_RTC) += pmic_rtc.o
obj-$(CONFIG_MXC_MC13892_LIGHT) += pmic_light.o
obj-$(CONFIG_MXC_MC13892_BATTERY) += pmic_battery.o
#obj-$(CONFIG_MXC_MC13892_CONNECTIVITY) += pmic_convity.o
#obj-$(CONFIG_MXC_MC13892_POWER) += pmic_power.o
