#
# Amlogic MMC specific Makefile
#

obj-$(CONFIG_AMLOGIC_MMC)	+= amlsd.o amlsd_of.o emmc_partitions.o aml_sd_emmc.o emmc_key.o aml_sd_emmc_v3.o

obj-$(CONFIG_AMLOGIC_M8B_MMC)	+= aml_sdhc_m8.o aml_sdio.o
