obj-$(CONFIG_AMLOGIC_SND_SOC_AUGE)	+= audio_controller.o \
						audio_io.o \
						clocks.o \
						card.o \
						card_utils.o \
						tdm.o \
						tdm_hw.o \
						spdif.o \
						spdif_hw.o \
						pdm.o \
						pdm_hw.o \
						pdm_hw_coeff.o \
						iomap.o \
						ddr_mngr.o \
						loopback_hw.o \
						audio_utils.o
