/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2022 MediaTek Inc.
 */

#ifndef __SENINF_REG_H__
#define __SENINF_REG_H__

#include <linux/bits.h>

#define SENINF_TOP_CTRL							0x0000
#define SENINF_TOP_CTRL_MUX_LP_MODE					BIT(31)
#define SENINF_TOP_CTRL_SENINF_PCLK_EN					BIT(10)
#define SENINF_TOP_CTRL_SENINF2_PCLK_EN					BIT(11)
#define SENINF_TOP_MUX_CTRL						0x0008
#define SENINF_TOP_CAM_MUX_CTRL						0x0010
#define SENINF_TOP_PHY_SENINF_CTL_CSI0					0x001c
#define SENINF_TOP_PHY_SENINF_CTL_CSI0_DPHY_MODE			BIT(0)
#define SENINF_TOP_PHY_SENINF_CTL_CSI0_CK_SEL_1				GENMASK(10, 8)
#define SENINF_TOP_PHY_SENINF_CTL_CSI0_CK_SEL_2				GENMASK(13, 12)
#define SENINF_TOP_PHY_SENINF_CTL_CSI0_PHY_SENINF_LANE_MUX_CSI0_EN	BIT(31)
#define SENINF_TOP_PHY_SENINF_CTL_CSI1					0x0020
#define SENINF_TOP_PHY_SENINF_CTL_CSI1_DPHY_MODE			BIT(0)
#define SENINF_TOP_PHY_SENINF_CTL_CSI1_CK_SEL_1				GENMASK(10, 8)
#define SENINF_TOP_PHY_SENINF_CTL_CSI1_PHY_SENINF_LANE_MUX_CSI1_EN	BIT(31)
#define SENINF_CTRL							0x0200
#define SENINF_CTRL_SENINF_EN						BIT(0)
#define SENINF_CTRL_CSI2_SW_RST						BIT(7)
#define SENINF_CTRL_SENINF_SRC_SEL					GENMASK(14, 12)
#define SENINF_CTRL_PAD2CAM_DATA_SEL					GENMASK(30, 28)
#define SENINF_CTRL_EXT							0x0204
#define SENINF_CTRL_EXT_SENINF_TESTMDL_IP_EN				BIT(1)
#define SENINF_CTRL_EXT_SENINF_NCSI2_IP_EN				BIT(5)
#define SENINF_CTRL_EXT_SENINF_CSI2_IP_EN				BIT(6)
#define SENINF_TG1_PH_CNT						0x0600
#define SENINF_TG1_SEN_CK						0x0604
#define SENINF_TG1_TM_CTL						0x0608
#define SENINF_TG1_TM_CTL_TM_EN						BIT(0)
#define SENINF_TG1_TM_CTL_TM_FMT					BIT(2)
#define SENINF_TG1_TM_CTL_TM_PAT					GENMASK(7, 4)
#define SENINF_TG1_TM_CTL_TM_VSYNC					GENMASK(15, 8)
#define SENINF_TG1_TM_CTL_TM_DUMMYPXL					GENMASK(23, 16)
#define SENINF_TG1_TM_SIZE						0x060c
#define SENINF_TG1_TM_SIZE_TM_LINE					GENMASK(29, 16)
#define SENINF_TG1_TM_SIZE_TM_PXL					GENMASK(12, 0)
#define SENINF_TG1_TM_CLK						0x0610
#define TEST_MODEL_CLK_DIVIDED_CNT					8
#define SENINF_TG1_TM_STP						0x0614
#define TIME_STAMP_DIVIDER						1
#define MIPI_RX_CON24_CSI0						0x0824
#define MIPI_RX_CON24_CSI0_CSI0_BIST_LN0_MUX				GENMASK(25, 24)
#define MIPI_RX_CON24_CSI0_CSI0_BIST_LN1_MUX				GENMASK(27, 26)
#define MIPI_RX_CON24_CSI0_CSI0_BIST_LN2_MUX				GENMASK(29, 28)
#define MIPI_RX_CON24_CSI0_CSI0_BIST_LN3_MUX				GENMASK(31, 30)
#define SENINF_CSI2_CTL							0x0a00
#define SENINF_CSI2_CTL_DATA_LANE0_EN					BIT(0)
#define SENINF_CSI2_CTL_DATA_LANE1_EN					BIT(1)
#define SENINF_CSI2_CTL_DATA_LANE2_EN					BIT(2)
#define SENINF_CSI2_CTL_DATA_LANE3_EN					BIT(3)
#define SENINF_CSI2_CTL_CLOCK_LANE_EN					BIT(4)
#define SENINF_CSI2_CTL_HSRX_DET_EN					BIT(7)
#define SENINF_CSI2_CTL_ED_SEL						BIT(16)
#define DATA_HEADER_ORDER_DI_WCL_WCH					1
#define SENINF_CSI2_CTL_HS_TRAIL_EN					BIT(25)
#define SENINF_CSI2_CTL_CLOCK_HS_OPTION					BIT(27)
#define SENINF_CSI2_LNRD_TIMING						0x0a08
#define SENINF_CSI2_LNRD_TIMING_DATA_SETTLE_PARAMETER			GENMASK(15, 8)
#define SENINF_CSI2_DPCM						0x0a0c
#define SENINF_CSI2_DPCM_DI_30_DPCM_EN					BIT(7)
#define SENINF_CSI2_DPCM_DI_2A_DPCM_EN					BIT(15)
#define SENINF_CSI2_INT_EN						0x0a10
#define SENINF_CSI2_INT_STATUS						0x0a14
#define SENINF_CSI2_DGB_SEL						0x0a18
#define SENINF_CSI2_DGB_SEL_DEBUG_SEL					GENMASK(7, 0)
#define SENINF_CSI2_DGB_SEL_DEBUG_EN					BIT(31)
#define SENINF_CSI2_SPARE0						0x0a20
#define SENINF_CSI2_LNRC_FSM						0x0a28
#define SENINF_CSI2_HS_TRAIL						0x0a40
#define SENINF_CSI2_HS_TRAIL_HS_TRAIL_PARAMETER				GENMASK(7, 0)
#define SENINF_CSI2_RESYNC_MERGE_CTL					0x0a74
#define SENINF_CSI2_RESYNC_MERGE_CTL_CPHY_LANE_RESYNC_CNT		GENMASK(2, 0)
#define SENINF_CSI2_RESYNC_MERGE_CTL_BYPASS_LANE_RESYNC			BIT(10)
#define SENINF_CSI2_RESYNC_MERGE_CTL_CDPHY_SEL				BIT(11)
#define SENINF_CSI2_MODE						0x0ae8
#define SENINF_CSI2_MODE_CSR_CSI2_MODE					GENMASK(7, 0)
#define SENINF_CSI2_MODE_CSR_CSI2_HEADER_LEN				GENMASK(10, 8)
#define SENINF_CSI2_DPHY_SYNC						0x0b20
#define SENINF_CSI2_DPHY_SYNC_SYNC_SEQ_MASK_0				GENMASK(15, 0)
#define SENINF_CSI2_DPHY_SYNC_SYNC_SEQ_PAT_0				GENMASK(31, 16)
#define SENINF_MUX_CTRL							0x0d00
#define SENINF_MUX_CTRL_SENINF_MUX_SW_RST				BIT(0)
#define SENINF_MUX_CTRL_SENINF_IRQ_SW_RST				BIT(1)
#define SENINF_MUX_CTRL_SENINF_HSYNC_MASK				BIT(7)
#define SENINF_MUX_CTRL_SENINF_PIX_SEL					BIT(8)
#define SENINF_MUX_CTRL_SENINF_VSYNC_POL				BIT(9)
#define SENINF_MUX_CTRL_SENINF_HSYNC_POL				BIT(10)
#define SENINF_MUX_CTRL_SENINF_SRC_SEL					GENMASK(15, 12)
#define SENINF_MUX_CTRL_FIFO_PUSH_EN					GENMASK(21, 16)
#define FIFO_PUSH_EN_NORMAL_MODE					0x1f
#define FIFO_PUSH_EN_JPEG_2_PIXEL_MODE					0x1e
#define SENINF_MUX_CTRL_FIFO_FLUSH_EN					GENMASK(28, 22)
#define FIFO_FLUSH_EN_NORMAL_MODE					0x1b
#define FIFO_FLUSH_EN_JPEG_2_PIXEL_MODE					0x18
#define SENINF_MUX_CTRL_FIFO_FULL_WR_EN					GENMASK(29, 28)
#define SENINF_MUX_CTRL_SENINF_MUX_EN					BIT(31)
#define SENINF_MUX_INTEN						0x0d04
#define SENINF_MUX_SPARE						0x0d2c
#define SENINF_MUX_CTRL_EXT						0x0d3c
#define SENINF_MUX_CTRL_EXT_SENINF_SRC_SEL_EXT				GENMASK(1, 0)
#define SENINF_MUX_CTRL_EXT_SENINF_PIX_SEL_EXT				BIT(4)

#endif /* __SENINF_REG_H__ */
