obj-$(CONFIG_AMLOGIC_HDMITX)		+= hdmitx20.o

hdmitx20-objs := hdmi_tx_main.o hdmi_tx_video.o hdmi_tx_audio.o hdmi_tx_edid.o \
		 hdmi_tx_audio.o hdmi_tx_hdcp.o hdmi_tx_scdc.o \

obj-$(CONFIG_AMLOGIC_HDMITX) += hw/

#EXTRA_CFLAGS += -O2
