ifeq ($(CONFIG_OF),y)

# Keep at91 dtb files sorted alphabetically for each SoC
# rm9200
dtb-$(CONFIG_ARCH_AT91) += at91rm9200ek.dtb
dtb-$(CONFIG_ARCH_AT91) += mpa1600.dtb
# sam9260
dtb-$(CONFIG_ARCH_AT91) += animeo_ip.dtb
dtb-$(CONFIG_ARCH_AT91) += at91-qil_a9260.dtb
dtb-$(CONFIG_ARCH_AT91) += aks-cdu.dtb
dtb-$(CONFIG_ARCH_AT91) += ethernut5.dtb
dtb-$(CONFIG_ARCH_AT91) += evk-pro3.dtb
dtb-$(CONFIG_ARCH_AT91) += tny_a9260.dtb
dtb-$(CONFIG_ARCH_AT91) += usb_a9260.dtb
# sam9263
dtb-$(CONFIG_ARCH_AT91) += at91sam9263ek.dtb
dtb-$(CONFIG_ARCH_AT91) += tny_a9263.dtb
dtb-$(CONFIG_ARCH_AT91) += usb_a9263.dtb
# sam9g20
dtb-$(CONFIG_ARCH_AT91) += at91-foxg20.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9g20ek.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9g20ek_2mmc.dtb
dtb-$(CONFIG_ARCH_AT91) += kizbox.dtb
dtb-$(CONFIG_ARCH_AT91) += tny_a9g20.dtb
dtb-$(CONFIG_ARCH_AT91) += usb_a9g20.dtb
dtb-$(CONFIG_ARCH_AT91) += usb_a9g20_lpw.dtb
# sam9g45
dtb-$(CONFIG_ARCH_AT91) += at91sam9m10g45ek.dtb
dtb-$(CONFIG_ARCH_AT91) += pm9g45.dtb
# sam9n12
dtb-$(CONFIG_ARCH_AT91) += at91sam9n12ek.dtb
# sam9x5
dtb-$(CONFIG_ARCH_AT91) += at91-ariag25.dtb
dtb-$(CONFIG_ARCH_AT91) += at91-cosino_mega2560.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9g15ek.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9g25ek.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9g35ek.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9x25ek.dtb
dtb-$(CONFIG_ARCH_AT91) += at91sam9x35ek.dtb
# sama5d3
dtb-$(CONFIG_ARCH_AT91)	+= at91-sama5d3_xplained.dtb
dtb-$(CONFIG_ARCH_AT91)	+= sama5d31ek.dtb
dtb-$(CONFIG_ARCH_AT91)	+= sama5d33ek.dtb
dtb-$(CONFIG_ARCH_AT91)	+= sama5d34ek.dtb
dtb-$(CONFIG_ARCH_AT91)	+= sama5d35ek.dtb
dtb-$(CONFIG_ARCH_AT91)	+= sama5d36ek.dtb

dtb-$(CONFIG_ARCH_ATLAS6) += atlas6-evb.dtb
dtb-$(CONFIG_ARCH_BCM2835) += bcm2835-rpi-b.dtb
dtb-$(CONFIG_ARCH_BCM_MOBILE) += bcm11351-brt.dtb \
	bcm28155-ap.dtb
dtb-$(CONFIG_ARCH_BCM2835) += bcm2835-rpi-b.dtb
dtb-$(CONFIG_ARCH_BERLIN) += \
	berlin2-sony-nsz-gs7.dtb	\
	berlin2cd-google-chromecast.dtb
dtb-$(CONFIG_ARCH_DAVINCI) += da850-enbw-cmc.dtb \
	da850-evm.dtb
dtb-$(CONFIG_ARCH_DOVE) += dove-cm-a510.dtb \
	dove-cubox.dtb \
	dove-d2plug.dtb \
	dove-d3plug.dtb \
	dove-dove-db.dtb
dtb-$(CONFIG_ARCH_EFM32) += efm32gg-dk3750.dtb
dtb-$(CONFIG_ARCH_EXYNOS) += exynos4210-origen.dtb \
	exynos4210-smdkv310.dtb \
	exynos4210-trats.dtb \
	exynos4210-universal_c210.dtb \
	exynos4412-odroidx.dtb \
	exynos4412-origen.dtb \
	exynos4412-smdk4412.dtb \
	exynos4412-tiny4412.dtb \
	exynos4412-trats2.dtb \
	exynos5250-arndale.dtb \
	exynos5250-smdk5250.dtb \
	exynos5250-snow.dtb \
	exynos5420-arndale-octa.dtb \
	exynos5420-smdk5420.dtb \
	exynos5440-sd5v1.dtb \
	exynos5440-ssdk5440.dtb
dtb-$(CONFIG_ARCH_HI3xxx) += hi3620-hi4511.dtb
dtb-$(CONFIG_ARCH_HIGHBANK) += highbank.dtb \
	ecx-2000.dtb
dtb-$(CONFIG_ARCH_INTEGRATOR) += integratorap.dtb \
	integratorcp.dtb
dtb-$(CONFIG_ARCH_LPC32XX) += ea3250.dtb phy3250.dtb
dtb-$(CONFIG_ARCH_KIRKWOOD) += kirkwood-cloudbox.dtb \
	kirkwood-db-88f6281.dtb \
	kirkwood-db-88f6282.dtb \
	kirkwood-dns320.dtb \
	kirkwood-dns325.dtb \
	kirkwood-dockstar.dtb \
	kirkwood-dreamplug.dtb \
	kirkwood-goflexnet.dtb \
	kirkwood-guruplug-server-plus.dtb \
	kirkwood-ib62x0.dtb \
	kirkwood-iconnect.dtb \
	kirkwood-iomega_ix2_200.dtb \
	kirkwood-is2.dtb \
	kirkwood-km_kirkwood.dtb \
	kirkwood-laplug.dtb \
	kirkwood-lschlv2.dtb \
	kirkwood-lsxhl.dtb \
	kirkwood-mplcec4.dtb \
	kirkwood-mv88f6281gtw-ge.dtb \
	kirkwood-netgear_readynas_duo_v2.dtb \
	kirkwood-netgear_readynas_nv+_v2.dtb \
	kirkwood-ns2.dtb \
	kirkwood-ns2lite.dtb \
	kirkwood-ns2max.dtb \
	kirkwood-ns2mini.dtb \
	kirkwood-nsa310.dtb \
	kirkwood-nsa310a.dtb \
	kirkwood-openblocks_a6.dtb \
	kirkwood-openblocks_a7.dtb \
	kirkwood-sheevaplug.dtb \
	kirkwood-sheevaplug-esata.dtb \
	kirkwood-topkick.dtb \
	kirkwood-ts219-6281.dtb \
	kirkwood-ts219-6282.dtb
dtb-$(CONFIG_ARCH_MARCO) += marco-evb.dtb
dtb-$(CONFIG_ARCH_MOXART) += moxart-uc7112lx.dtb
dtb-$(CONFIG_ARCH_MSM) += qcom-msm8660-surf.dtb \
	qcom-msm8960-cdp.dtb \
	qcom-apq8074-dragonboard.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-370-db.dtb \
	armada-370-mirabox.dtb \
	armada-370-netgear-rn102.dtb \
	armada-370-netgear-rn104.dtb \
	armada-370-rd.dtb \
	armada-xp-axpwifiap.dtb \
	armada-xp-db.dtb \
	armada-xp-gp.dtb \
	armada-xp-netgear-rn2120.dtb \
	armada-xp-matrix.dtb \
	armada-xp-openblocks-ax3-4.dtb
dtb-$(CONFIG_ARCH_MXC) += \
	imx25-karo-tx25.dtb \
	imx25-pdk.dtb \
	imx27-apf27.dtb \
	imx27-apf27dev.dtb \
	imx27-pdk.dtb \
	imx27-phytec-phycore-som.dtb \
	imx27-phytec-phycore-rdk.dtb \
	imx27-phytec-phycard-s-som.dtb \
	imx27-phytec-phycard-s-rdk.dtb \
	imx31-bug.dtb \
	imx51-apf51.dtb \
	imx51-apf51dev.dtb \
	imx51-babbage.dtb \
	imx51-nitrogen51_vm.dtb \
	imx53-ard.dtb \
	imx53-evk.dtb \
	imx53-m53evk.dtb \
	imx53-mba53.dtb \
	imx53-qsb.dtb \
	imx53-smd.dtb \
	imx6dl-a.dtb \
	imx6dl-ash.dtb \
	imx6dl-bt.dtb \
	imx6dl-cubox-i.dtb \
	imx6dl-hummingboard.dtb \
	imx6dl-hp.dtb \
	imx6dl-mcs.dtb \
	imx6dl-mtp.dtb \
	imx6dl-nit6xlite.dtb \
	imx6dl-nitrogen6_max.dtb \
	imx6dl-nitrogen6_vm.dtb \
	imx6dl-nitrogen6_vm-magstripe.dtb \
	imx6dl-nitrogen6_vm-pt.dtb \
	imx6dl-nitrogen6x.dtb \
	imx6dl-per.dtb \
	imx6dl-rc.dtb \
	imx6dl-sabreauto.dtb \
	imx6dl-sabreauto-flexcan1.dtb \
	imx6dl-sabreauto-ecspi.dtb \
	imx6dl-sabreauto-gpmi-weim.dtb \
	imx6dl-sabresd.dtb \
	imx6dl-sabresd-btwifi.dtb \
	imx6dl-sabresd-enetirq.dtb \
	imx6dl-sabresd-ldo.dtb \
	imx6dl-sabresd-pf200.dtb \
	imx6dl-sabresd-hdcp.dtb \
	imx6dl-sp.dtb \
	imx6dl-wandboard.dtb \
	imx6q-arm2.dtb \
	imx6q-bt.dtb \
	imx6q-bt2.dtb \
	imx6q-cob.dtb \
	imx6q-cubox-i.dtb \
	imx6q-cnt.dtb \
	imx6q-eo.dtb \
	imx6q-h4.dtb \
	imx6q-insp.dtb \
	imx6q-ioc.dtb \
	imx6q-jlm.dtb \
	imx6q-ls.dtb \
	imx6q-mcs.dtb \
	imx6q-mtp.dtb \
	imx6q-phytec-pbab01.dtb \
	imx6q-nitrogen6_max.dtb \
	imx6q-nitrogen6_som2.dtb \
	imx6q-nitrogen6x.dtb \
	imx6q-nitrogen6x-careview.dtb \
	imx6q-nw2.dtb \
	imx6q-per.dtb \
	imx6q-s.dtb \
	imx6q-sabreauto.dtb \
	imx6q-sabreauto-flexcan1.dtb \
	imx6q-sabreauto-ecspi.dtb \
	imx6q-sabreauto-gpmi-weim.dtb \
	imx6qp-mtp.dtb \
	imx6qp-nitrogen6_max.dtb \
	imx6qp-sabreauto.dtb \
	imx6qp-sabreauto-ecspi.dtb \
	imx6qp-sabreauto-flexcan1.dtb \
	imx6qp-sabreauto-gpmi-weim.dtb \
	imx6qp-sabresd.dtb \
	imx6qp-sabresd-btwifi.dtb \
	imx6qp-sabresd-ldo.dtb \
	imx6qp-sabresd-hdcp.dtb \
	imx6q-sabrelite.dtb \
	imx6q-sabresd.dtb \
	imx6q-sabresd-btwifi.dtb \
	imx6q-sabresd-enetirq.dtb \
	imx6q-sabresd-ldo.dtb \
	imx6q-sabresd-hdcp.dtb \
	imx6q-sbc6x.dtb \
	imx6q-snap.dtb \
	imx6q-ta.dtb \
	imx6q-udoo.dtb \
	imx6q-usd.dtb \
	imx6q-utc.dtb \
	imx6q-vp.dtb \
	imx6q-wandboard.dtb \
	imx6sl-evk.dtb \
	imx6sl-evk-btwifi.dtb \
	imx6sl-evk-csi.dtb \
	imx6sl-evk-ldo.dtb \
	imx6sl-evk-pf200.dtb \
	imx6sl-evk-uart.dtb \
	imx6sx-14x14-arm2.dtb \
	imx6sx-17x17-arm2.dtb \
	imx6sx-17x17-arm2-ldo.dtb \
	imx6sx-17x17-arm2-ecspi.dtb \
	imx6sx-17x17-arm2-gpmi-weim.dtb \
	imx6sx-17x17-arm2-mlb.dtb \
	imx6sx-17x17-arm2-sai.dtb \
	imx6sx-17x17-arm2-spdif.dtb \
	imx6sx-17x17-arm2-ssi.dtb \
	imx6sx-19x19-arm2.dtb \
	imx6sx-19x19-arm2-ldo.dtb \
	imx6sx-19x19-arm2-mqs.dtb \
	imx6sx-19x19-arm2-sai.dtb \
	imx6sx-19x19-arm2-csi.dtb \
	imx6sx-19x19-arm2-lcdif1.dtb \
	imx6sx-19x19-arm2-gpmi-weim.dtb \
	imx6sx-nitrogen6_scm.dtb \
	imx6sx-nitrogen6sx.dtb \
	imx6sx-nitrogen6sx-m4.dtb \
	imx6sx-sdb.dtb \
	imx6sx-sdb-btwifi.dtb \
	imx6sx-sdb-ldo.dtb \
	imx6sx-sdb-mqs.dtb \
	imx6sx-sdb-reva.dtb \
	imx6sx-sdb-reva-ldo.dtb \
	imx6sx-sdb-sai.dtb \
	imx6sx-sabreauto.dtb \
	imx6sx-sabreauto-m4.dtb \
	imx6sx-sdb-lcdif1.dtb \
	imx6ul-14x14-lpddr2-arm2.dtb \
	imx6ul-14x14-ddr3-arm2.dtb \
	imx6ul-14x14-ddr3-arm2-adc.dtb \
	imx6ul-14x14-ddr3-arm2-emmc.dtb	\
	imx6ul-14x14-ddr3-arm2-flexcan2.dtb \
	imx6ul-14x14-ddr3-arm2-gpmi-weim.dtb \
	imx6ul-14x14-ddr3-arm2-lcdif.dtb \
	imx6ul-14x14-ddr3-arm2-mqs.dtb \
	imx6ul-14x14-ddr3-arm2-spdif.dtb \
	imx6ul-14x14-ddr3-arm2-wm8958.dtb \
	imx6ul-14x14-evk.dtb \
	imx6ul-14x14-evk-btwifi.dtb \
	imx6ul-14x14-evk-csi.dtb \
	imx6ul-9x9-evk.dtb \
	imx6ul-9x9-evk-btwifi.dtb \
	imx6ul-9x9-evk-ldo.dtb \
	imx6ul-9x9-evk-csi.dtb \
	vf610-cosmic.dtb \
	imx6sx-sdb-emmc.dtb \
	imx6sx-sdb-m4.dtb \
	vf610-twr.dtb \
	imx7d-12x12-lpddr3-arm2.dtb \
	imx7d-12x12-ddr3-arm2.dtb \
	imx7d-12x12-lpddr3-arm2-ecspi.dtb \
	imx7d-12x12-lpddr3-arm2-enet.dtb \
	imx7d-12x12-lpddr3-arm2-flexcan.dtb \
	imx7d-12x12-lpddr3-arm2-qspi.dtb \
	imx7d-12x12-lpddr3-arm2-sai.dtb \
	imx7d-12x12-lpddr3-arm2-sim.dtb \
	imx7d-12x12-lpddr3-arm2-m4.dtb \
	imx7d-12x12-lpddr3-arm2-pcie.dtb \
	imx7d-12x12-lpddr3-arm2-mipi_dsi.dtb \
	imx7d-12x12-lpddr3-arm2-mqs.dtb \
	imx7d-19x19-lpddr2-arm2.dtb \
	imx7d-19x19-lpddr3-arm2.dtb \
	imx7d-19x19-ddr3-arm2.dtb \
	imx7d-19x19-ddr3-arm2-csi.dtb \
	imx7d-19x19-ddr3-arm2-sai.dtb \
	imx7d-19x19-ddr3-arm2-mipi.dtb \
	imx7d-nitrogen7.dtb \
	imx7d-nitrogen7-m4.dtb \
	imx7d-sdb.dtb \
	imx7d-sdb-enet.dtb \
	imx7d-sdb-epdc.dtb \
	imx7d-sdb-gpmi-weim.dtb \
	imx7d-sdb-hdmi-audio.dtb \
	imx7d-sdb-qspi.dtb \
	imx7d-sdb-sim.dtb \
	imx7d-sdb-touch.dtb \
	imx7d-sdb-wm8960.dtb \
	imx7d-sdb-m4.dtb
dtb-$(CONFIG_ARCH_MXS) += imx23-evk.dtb \
	imx23-olinuxino.dtb \
	imx23-stmp378x_devb.dtb \
	imx28-apf28.dtb \
	imx28-apf28dev.dtb \
	imx28-apx4devkit.dtb \
	imx28-cfa10036.dtb \
	imx28-cfa10037.dtb \
	imx28-cfa10049.dtb \
	imx28-cfa10055.dtb \
	imx28-cfa10056.dtb \
	imx28-cfa10057.dtb \
	imx28-cfa10058.dtb \
	imx28-evk.dtb \
	imx28-m28cu3.dtb \
	imx28-m28evk.dtb \
	imx28-sps1.dtb \
	imx28-tx28.dtb
dtb-$(CONFIG_ARCH_NOMADIK) += ste-nomadik-s8815.dtb
dtb-$(CONFIG_ARCH_NSPIRE) += nspire-cx.dtb \
	nspire-tp.dtb \
	nspire-clp.dtb
dtb-$(CONFIG_ARCH_OMAP2PLUS) += omap2420-h4.dtb \
	omap2430-sdp.dtb \
	omap2420-n800.dtb \
	omap2420-n810.dtb \
	omap2420-n810-wimax.dtb \
	omap3430-sdp.dtb \
	omap3-beagle.dtb \
	omap3-cm-t3730.dtb \
	omap3-sbc-t3730.dtb \
	omap3-devkit8000.dtb \
	omap3-beagle-xm.dtb \
	omap3-evm.dtb \
	omap3-evm-37xx.dtb \
	omap3-ldp.dtb \
	omap3-n900.dtb \
	omap3-n9.dtb \
	omap3-n950.dtb \
	omap3-overo-tobi.dtb \
	omap3-overo-storm-tobi.dtb \
	omap3-gta04.dtb \
	omap3-igep0020.dtb \
	omap3-igep0030.dtb \
	omap3-zoom3.dtb \
	omap4-panda.dtb \
	omap4-panda-a4.dtb \
	omap4-panda-es.dtb \
	omap4-var-som.dtb \
	omap4-sdp.dtb \
	omap4-sdp-es23plus.dtb \
	omap5-uevm.dtb \
	am335x-evm.dtb \
	am335x-evmsk.dtb \
	am335x-bone.dtb \
	am335x-boneblack.dtb \
	am335x-nano.dtb \
	am335x-base0033.dtb \
	am3517-evm.dtb \
	am3517_mt_ventoux.dtb \
	am43x-epos-evm.dtb \
	dra7-evm.dtb
dtb-$(CONFIG_ARCH_ORION5X) += orion5x-lacie-ethernet-disk-mini-v2.dtb
dtb-$(CONFIG_ARCH_PRIMA2) += prima2-evb.dtb
dtb-$(CONFIG_ARCH_U8500) += ste-snowball.dtb \
	ste-hrefprev60-stuib.dtb \
	ste-hrefprev60-tvk.dtb \
	ste-hrefv60plus-stuib.dtb \
	ste-hrefv60plus-tvk.dtb \
	ste-ccu8540.dtb \
	ste-ccu9540.dtb
dtb-$(CONFIG_ARCH_S3C24XX) += s3c2416-smdk2416.dtb
dtb-$(CONFIG_ARCH_S3C64XX) += s3c6410-mini6410.dtb \
	s3c6410-smdk6410.dtb
dtb-$(CONFIG_ARCH_SHMOBILE_LEGACY) += emev2-kzm9d.dtb \
	r7s72100-genmai.dtb \
	r7s72100-genmai-reference.dtb \
	r8a7740-armadillo800eva.dtb \
	r8a7778-bockw.dtb \
	r8a7778-bockw-reference.dtb \
	r8a7740-armadillo800eva-reference.dtb \
	r8a7779-marzen.dtb \
	r8a7779-marzen-reference.dtb \
	r8a7791-koelsch.dtb \
	r8a7790-lager.dtb \
	sh73a0-kzm9g.dtb \
	sh73a0-kzm9g-reference.dtb \
	r8a73a4-ape6evm.dtb \
	r8a73a4-ape6evm-reference.dtb \
	sh7372-mackerel.dtb
dtb-$(CONFIG_ARCH_SHMOBILE_MULTI) += emev2-kzm9d.dtb \
	r7s72100-genmai-reference.dtb \
	r8a7791-koelsch.dtb \
	r8a7790-lager.dtb
dtb-$(CONFIG_ARCH_SOCFPGA) += socfpga_arria5_socdk.dtb \
	socfpga_cyclone5_socdk.dtb \
	socfpga_cyclone5_sockit.dtb \
	socfpga_vt.dtb
dtb-$(CONFIG_ARCH_SPEAR13XX) += spear1310-evb.dtb \
	spear1340-evb.dtb
dtb-$(CONFIG_ARCH_SPEAR3XX)+= spear300-evb.dtb \
	spear310-evb.dtb \
	spear320-evb.dtb \
	spear320-hmi.dtb
dtb-$(CONFIG_ARCH_SPEAR6XX)+= spear600-evb.dtb
dtb-$(CONFIG_ARCH_STI)+= stih415-b2000.dtb \
	stih416-b2000.dtb \
	stih415-b2020.dtb \
	stih416-b2020.dtb
dtb-$(CONFIG_ARCH_SUNXI) += \
	sun4i-a10-a1000.dtb \
	sun4i-a10-cubieboard.dtb \
	sun4i-a10-mini-xplus.dtb \
	sun4i-a10-hackberry.dtb \
	sun5i-a10s-olinuxino-micro.dtb \
	sun5i-a13-olinuxino.dtb \
	sun5i-a13-olinuxino-micro.dtb \
	sun6i-a31-colombus.dtb \
	sun7i-a20-cubieboard2.dtb \
	sun7i-a20-cubietruck.dtb \
	sun7i-a20-olinuxino-micro.dtb
dtb-$(CONFIG_ARCH_TEGRA) += tegra20-harmony.dtb \
	tegra20-iris-512.dtb \
	tegra20-medcom-wide.dtb \
	tegra20-paz00.dtb \
	tegra20-plutux.dtb \
	tegra20-seaboard.dtb \
	tegra20-tec.dtb \
	tegra20-trimslice.dtb \
	tegra20-ventana.dtb \
	tegra20-whistler.dtb \
	tegra30-beaver.dtb \
	tegra30-cardhu-a02.dtb \
	tegra30-cardhu-a04.dtb \
	tegra114-dalmore.dtb \
	tegra124-venice2.dtb
dtb-$(CONFIG_ARCH_VERSATILE) += versatile-ab.dtb \
	versatile-pb.dtb
dtb-$(CONFIG_ARCH_U300) += ste-u300.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += vexpress-v2p-ca5s.dtb \
	vexpress-v2p-ca9.dtb \
	vexpress-v2p-ca15-tc1.dtb \
	vexpress-v2p-ca15_a7.dtb
dtb-$(CONFIG_ARCH_VIRT) += xenvm-4.2.dtb
dtb-$(CONFIG_ARCH_VT8500) += vt8500-bv07.dtb \
	wm8505-ref.dtb \
	wm8650-mid.dtb \
	wm8750-apc8750.dtb \
	wm8850-w70v2.dtb
dtb-$(CONFIG_ARCH_ZYNQ) += zynq-zc702.dtb \
	zynq-zc706.dtb \
	zynq-zed.dtb

targets += dtbs
targets += $(dtb-y)
endif

# *.dtb used to be generated in the directory above. Clean out the
# old build results so people don't accidentally use them.
dtbs: $(addprefix $(obj)/, $(dtb-y))
	$(Q)rm -f $(obj)/../*.dtb

clean-files := *.dtb
