/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __MTK_CAMSV_REGS_H__
#define __MTK_CAMSV_REGS_H__

#define CAMSV_MODULE_EN				0x0010
#define CAMSV_CLK_EN				0x0030
#define CAMSV_INT_EN				0x0018
#define CAMSV_INT_STATUS			0x001c
#define CAMSV_FMT_SEL				0x0014
#define CAMSV_SW_CTL				0x0020
#define CAMSV_PAK				0x004c

#define CAMSV_TG_SEN_MODE			0x0130
#define CAMSV_TG_VF_CON				0x0134
#define CAMSV_TG_SEN_GRAB_PXL			0x0138
#define CAMSV_TG_SEN_GRAB_LIN			0x013c
#define CAMSV_TG_PATH_CFG			0x0140
#define CAMSV_TG_TIME_STAMP			0x01a0
#define CAMSV_TG_TIME_STAMP_CTL			0x01b0

#define CAMSV_FBC_IMGO_CTL1			0x0a00
#define CAMSV_FBC_IMGO_CTL2			0x0a04
#define CAMSV_FBC_IMGO_ENQ_ADDR			0x0a08
#define CAMSV_IMGO_FBC				0x002c

#define CAMSV_IMGO_CON				0x043c
#define CAMSV_IMGO_CON2				0x0440
#define CAMSV_IMGO_CON3				0x0444
#define CAMSV_IMGO_BASE_ADDR			0x0420
#define CAMSV_IMGO_OFST_ADDR			0x0428
#define CAMSV_IMGO_XSIZE			0x0430
#define CAMSV_IMGO_YSIZE			0x0434
#define CAMSV_IMGO_STRIDE			0x0438
#define CAMSV_IMGO_FH_BASE_ADDR			0x0804
#define CAMSV_DMA_FH_EN				0x0800
#define CAMSV_DMA_RSV1				0x07b0
#define CAMSV_DMA_RSV6				0x07c4
#define CAMSV_SPECIAL_FUN_EN			0x0418
#define CAMSV_DCIF_SET				0x0058

#define CAMSV_IMGO_ERR_STAT			0x0760

#define CAMSV_DCIF_SET_MASK_DB_LOAD		BIT(7)

/* CAMSV_MODULE_EN bits */
#define CAMSV_MODULE_EN_IMGO_EN			BIT(4)
#define CAMSV_MODULE_EN_DB_EN			BIT(30)

#define CAMSV_TG_SEN_MODE_CMOS_EN		BIT(0)
#define CAMSV_TG_VF_CON_VFDATA_EN		BIT(0)
#define CAMSV_TG_VF_CON_SINGLE_MODE		BIT(1)

/* CAMSV_CLK_EN bits */
#define CAMSV_TG_DP_CLK_EN			BIT(0)
#define CAMSV_PAK_DP_CLK_EN			BIT(2)
#define CAMSV_DMA_DP_CLK_EN			BIT(15)

/* CAMSV_SW_CTL bits */
#define CAMSV_IMGO_RST_TRIG			BIT(0)
#define CAMSV_IMGO_RST_ST			BIT(1)
#define CAMSV_SW_RST				BIT(2)

/* IRQ BITS */
#define CAMSV_IRQ_VS1				BIT(0)
#define CAMSV_IRQ_TG1				BIT(1)
#define CAMSV_IRQ_TG2				BIT(2)
#define CAMSV_IRQ_EXPDON1			BIT(3)
#define CAMSV_IRQ_TG_ERR			BIT(4)
#define CAMSV_IRQ_TG_GBERR			BIT(5)
#define CAMSV_IRQ_TG_SOF_INT			BIT(6)
#define CAMSV_IRQ_TG_SOF_WAIT			BIT(7)
#define CAMSV_IRQ_TG_SOF_DROP			BIT(8)
#define CAMSV_IRQ_VS_ORG			BIT(9)
#define CAMSV_IRQ_DB_LOAD_ERR			BIT(10)
#define CAMSV_IRQ_PASS1_DON			BIT(11)
#define CAMSV_IRQ_SW_PASS1_DON			BIT(12)
#define CAMSV_IRQ_SUB_PASS1_DON			BIT(13)
#define CAMSV_IRQ_UFEO_ERR			BIT(14)
#define CAMSV_IRQ_UFEO_ERR_DROP			BIT(15)
#define CAMSV_IRQ_IMGO_ERR			BIT(16)
#define CAMSV_IRQ_IMGO_OVERR			BIT(17)
#define CAMSV_IRQ_IMGO_DROP			BIT(19)

#define INT_ST_MASK_CAMSV                                                      \
	(CAMSV_IRQ_TG_ERR | CAMSV_IRQ_TG_GBERR | \
	 CAMSV_IRQ_TG_SOF_INT | CAMSV_IRQ_PASS1_DON | CAMSV_IRQ_SW_PASS1_DON)

#define INT_ST_MASK_CAMSV_ERR                                                  \
	(CAMSV_IRQ_TG_ERR | CAMSV_IRQ_TG_GBERR | CAMSV_IRQ_IMGO_ERR | CAMSV_IRQ_DB_LOAD_ERR)

#endif /* __MTK_CAMSV_REGS_H__ */
