#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_AMLOGIC_INPUT_KEYBOARD) += keyboard/

obj-$(CONFIG_AMLOGIC_SARADC) += saradc/

obj-$(CONFIG_AMLOGIC_REMOTE) += remote/
