#
# Makefile for HDMI_RX.
#

obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_HDMI) += tvin_hdmirx.o
tvin_hdmirx-objs := hdmi_rx_wrapper.o hdmi_rx_hw.o hdmi_rx_drv.o \
		hdcp_rx_main.o hdmi_rx_eq.o \
		hdmi_rx_repeater.o hdmi_rx_pktinfo.o hdmi_rx_edid.o