#
# Makefile for HDMI_RX.
#

obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_HDMI) += tvin_hdmirx.o
tvin_hdmirx-objs := hdmi_rx_wrapper.o hdmi_rx_hw.o hdmirx_drv.o hdcp_main.o hdmi_rx_eq.o \
		hdmirx_repeater.o hdmi_rx_pktinfo.o

#obj-y			+= uart_hdmi.o
