#
# Makefile for the goodix gt9xx touchscreen drivers.
#
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_GT9XX)	+= gt9xx.o
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_GT9XX)	+= gt9xx_update.o
obj-$(CONFIG_AMLOGIC_TOUCHSCREEN_GT9XX)	+= goodix_tool.o
