#
# Makefile for VFM
#

obj-$(CONFIG_AMLOGIC_MEDIA_VFM)	+=	vfm.o
obj-$(CONFIG_AMLOGIC_MEDIA_VFM)	+=	vframe_provider.o
obj-$(CONFIG_AMLOGIC_MEDIA_VFM)	+=	vframe_receiver.o
obj-$(CONFIG_AMLOGIC_MEDIA_VFM)	+=	vftrace.o
