#
# Amlogic external hdmirx chips Makefile
#

obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_HDMI_EXT) += hdmirx_ext.o

hdmirx_ext-objs := hdmirx_ext_drv.o hdmirx_ext_attrs.o platform_iface.o \
		hdmirx_ext_hw_iface.o vdin_iface.o

obj-$(CONFIG_AMLOGIC_MEDIA_TVIN_HDMI_EXT_SII9135) += hw_sii9135/
