#
# Makefile for the MXS battery charger driver
#

obj-$(CONFIG_BATTERY_MXS) += mxs-battery.o

mxs-battery-objs := ddi_bc_api.o ddi_bc_hw.o ddi_bc_init.o \
		         ddi_bc_ramp.o ddi_bc_sm.o ddi_power_battery.o linux.o fiq.o

