boundary_camera-objs := boundary_camera_csi.o
obj-$(CONFIG_VIDEO_BOUNDARY_CAMERA) += boundary_camera.o

ov5640-objs := ov5640_sensor.o
obj-$(CONFIG_BOUNDARY_CAMERA_OV5640) += ov5640.o

tfp401-objs := tfp401_sensor.o
obj-$(CONFIG_BOUNDARY_CAMERA_HDMI_IN) += tfp401.o
