# MXS platfrom support
snd-soc-mxs-objs := mxs-pcm.o
snd-soc-mxs-dai-objs := mxs-dai.o
snd-soc-mxs-spdif-dai-objs := mxs-spdif-dai.o
snd-soc-mxs-devb-objs := mxs-devb.o
snd-soc-mxs-devb-spdif-objs := mxs-devb-spdif.o
snd-soc-mxs-adc-objs := mxs-adc.o
snd-soc-mxs-evk-adc-objs := mxs-evk-adc.o

obj-$(CONFIG_SND_MXS_SOC) += snd-soc-mxs.o
obj-$(CONFIG_SND_MXS_SOC_DAI) += snd-soc-mxs-dai.o
obj-$(CONFIG_SND_MXS_SOC_SPDIF_DAI) += snd-soc-mxs-spdif-dai.o
obj-$(CONFIG_SND_MXS_SOC_EVK_DEVB) += snd-soc-mxs-devb.o
obj-$(CONFIG_SND_MXS_SOC_EVK_DEVB_SPDIF) += snd-soc-mxs-devb-spdif.o
obj-$(CONFIG_SND_MXS_SOC_ADC) += snd-soc-mxs-adc.o
obj-$(CONFIG_SND_MXS_SOC_EVK_ADC) += snd-soc-mxs-evk-adc.o
